In [1]:
from IPython.display import Image

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

# chapter 4. 다차원 배열의 연산

## 산술 연산

### -  벡터간의 덧셈

- 동일한 원소를 가진 1차원 배열간의 덧셈, 벡터간의 덧셈은 새로운 벡터를 만듭니다.
- 1차원 배열의 __원소별 덧셈 연산__합니다.

![](numpy/04/04_1.png)

In [4]:
d = np.array([3,4])

In [5]:
d

array([3, 4])

In [6]:
e = np.array([5,6]) 

In [7]:
e

array([5, 6])

In [8]:
d + e

array([ 8, 10])

In [9]:
np.add(d, e)

array([ 8, 10])

In [10]:
f = np.array([1,2,3])

In [11]:
f

array([1, 2, 3])

In [12]:
try :
    f + e
except Exception as ex :
    print(ex)

operands could not be broadcast together with shapes (3,) (2,) 


### - 벡터간의 뺄셈

- 벡터간의 뺄셈도 덧셈과 동일하게 평행사변형을 만듭니다. 대신 반대 방향이라서 반대 방향의 평행사변형이 그려집니다.
- 1차원 배열의 __원소별 뺄셈처리__로 계산합니다.

![](numpy/04/04_2.png)

In [13]:
d = np.array([3,4])

In [14]:
d

array([3, 4])

In [15]:
e = np.array([5,6])

In [16]:
e

array([5, 6])

In [17]:
f= d - e

In [18]:
f

array([-2, -2])

In [19]:
np.subtract(d,e)

array([-2, -2])

In [20]:
d + (-e)

array([-2, -2])

In [21]:
np.add(d, np.negative(e))

array([-2, -2])

### -  스칼라 값을 벡터에 곱하기

- 특정 벡터가 있을 때 이 벡터를 특정 상수만큼 크기를 확장할 수 있습니다. 이를 스칼라 배라고 합니다. __벡터에 상수를 곱한 결과__입니다.

![](numpy/04/04_3.png)

In [22]:
d = np.array([2,3])

In [23]:
d

array([2, 3])

In [24]:
e = 3 * d

In [25]:
e

array([6, 9])

In [26]:
e = np.array([3,3]) * d

In [27]:
e

array([6, 9])

In [28]:
e = np.multiply(3, d)

In [29]:
e

array([6, 9])

In [30]:
e = np.multiply(np.array([3,3]), d)

In [31]:
e

array([6, 9])

In [32]:
e = 1/3 * d

In [33]:
e

array([0.66666667, 1.        ])

In [34]:
e = np.divide(d,3)

In [35]:
e

array([0.66666667, 1.        ])

In [36]:
e = np.multiply(d, (1/3))

In [37]:
e

array([0.66666667, 1.        ])

## 브로드캐스팅 이해하기

### - 브로트캐스팅

- 차원이 다른 배열간의 계산을 할 때에는 먼저 __원소별 계산__을 위해 __동일한 shape를 구성__합니다. 이를 브로트캐스팅이라고 합니다.

In [38]:
x = np.arange(10).reshape(2,5)

In [39]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
y = np.arange(5)

In [41]:
y

array([0, 1, 2, 3, 4])

In [42]:
z = np.broadcast(x,y)

In [43]:
z

In [44]:
print("shape : {}, dimension : {}".format(z.shape, z.ndim))

shape : (2, 5), dimension : 2


In [45]:
type(z)

numpy.broadcast

1차원 배열을 2차원 배열로 변환

In [46]:
for i in z :
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [47]:
t = x + y

In [48]:
t

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

### - 브로드캐스팅 처리 규칙

In [49]:
x1 = np.ones(3)

In [50]:
x1

array([1., 1., 1.])

In [51]:
x2 = np.ones((2,3))

In [52]:
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

__마지막 원소 갯수 확인__

In [53]:
x1.shape, x2.shape

((3,), (2, 3))

In [54]:
x1.shape[0]

3

In [55]:
x2.shape[0], x2.shape[1]

(2, 3)

In [56]:
x1.shape[0] == x2.shape[1]

True

__차원 추가__

In [57]:
x1 = x1[np.newaxis,]

In [58]:
x1.shape

(1, 3)

In [59]:
x1 = x1[np.newaxis,]

In [60]:
x1.shape ############ 새로운 차원은 앞에만 추가되는지?

(1, 1, 3)

In [61]:
##########차원 삭제는 어떻게 하는지?

__행을 하나 더 추가__

In [62]:
x1

array([[[1., 1., 1.]]])

In [63]:
x1 = np.vstack((x1[0])) ################

In [64]:
x1

array([[1., 1., 1.]])

### - 행벡터와 열벡터 브로드캐스팅 확장

- 행벡터와 열벡터의 연산은 __동일한 shape를 구성한 후__에 __원소별로 계산__합니다.

![](numpy/04/04_4.png)

In [65]:
x = np.arange(1,4)

In [66]:
x

array([1, 2, 3])

In [67]:
x1 = x.reshape(1,3)

In [68]:
x1

array([[1, 2, 3]])

In [69]:
x2 = x[np.newaxis,]

In [70]:
x2

array([[1, 2, 3]])

In [71]:
y = np.arange(1,4)

In [72]:
y

array([1, 2, 3])

In [73]:
y1 = y.reshape(3,1)

In [74]:
y1

array([[1],
       [2],
       [3]])

In [75]:
y2 = y[:,np.newaxis]

In [76]:
y2

array([[1],
       [2],
       [3]])

In [77]:
np.broadcast_arrays(x1,y1)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [78]:
x1 + y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## 행렬의 연산

### - 벡터의 내적

- 벡터의 내적은 두 벡터의 크기와 내각의 곱, 또는 두 벡터의 원소별 곱셈 후에 더해서 구할 수 있습니다.
- 보통 벡터 내적은 __두 벡터가 수직인지 확인__할 때 많이 사용됩니다.<br><br>
공식 : $
a \cdot b=|a| \times|b| \times \cos (\theta)
$

![](numpy/04/04_5.png)

In [79]:
a = np.array([3,4])

In [80]:
a

array([3, 4])

In [81]:
b = np.array([5,6])

In [82]:
b

array([5, 6])

In [83]:
a @ b

39

In [84]:
np.dot(a,b)

39

In [85]:
np.inner(a,b)

39

### - 벡터의 외적(cross product)

- 두 벡터의 외적은 두 벡터를 평면으로 인식한 후에 두 벡터가 만나는 점에 대하여 수직인 벡터를 구하는 것입니다.<br><br>
cross product :<br>
https://ko.wikipedia.org/wiki/%EB%B2%A1%ED%84%B0%EA%B3%B1 <br>
outer product : <br>
https://ko.wikipedia.org/wiki/%EC%99%B8%EC%A0%81

![](numpy/04/04_6.png)

In [86]:
a = np.array([1,4])
b = np.array([3,6])

In [87]:
np.cross(a,b)

array(-6)

In [88]:
c = np.array([1,4,3])
d = np.array([3,4,5])

In [89]:
np.cross(c,d)

array([ 8,  4, -8])

### - 행렬 dot product

- dot product는 A 행렬의 행과 B 행렬의 열 간의 원소를 곱해서 더한 값을 새로운 행렬의 A행렬의 0번 축의 위치와 B행렬의 1번 축의 위치에 해당하는 원소가 됩니다.<br><br>
$ a \cdot b=\sum_{n} a_{n} b_{n} $  <---------- 넘파이로 구현 시 : np.dot(a,b)

![](numpy/04/dot_product_1.png)

![](numpy/04/dot_product_2.png)

### - 행렬 dot product 계산

- 2개의 2행 2열의 배열을 만들고, dot 함수, dot 메소드, @ 연산자로 dot 연산을 실행합니다.

In [90]:
a = np.array([[3,4],[5,6]])

In [91]:
a

array([[3, 4],
       [5, 6]])

In [92]:
b = np.array([[5,6],[6,7]])

In [93]:
b

array([[5, 6],
       [6, 7]])

In [94]:
np.dot(a,b),                   a.dot(b),                   a@b 

(array([[39, 46],
        [61, 72]]),
 array([[39, 46],
        [61, 72]]),
 array([[39, 46],
        [61, 72]]))

### - 행렬 dot product 계산 : 행렬분해이용

- 두번째 행렬을 열벡터로 분해한 후에 dot product를 계산한 결과도 알아봅시다.

$
A b_{1}=A\left[\begin{array}{c}
b_{11} \\
b_{21} \\
\vdots \\
b_{n 1}
\end{array}\right]
$
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
$
A b_{2}=A\left[\begin{array}{c}
b_{12} \\
b_{22} \\
\vdots \\
b_{n 2}
\end{array}\right]
$
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
$
A b_{n}=A\left[\begin{array}{c}
b_{1n} \\
b_{2n} \\
\vdots \\
b_{n n}
\end{array}\right]
$

dot product 연산

In [95]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [96]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [98]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## 행렬식, 역행렬 처리하기

### - 행렬식

- 행렬식(determinant)은 정사각행렬일 때 이 원소들을 대응해서 값을 구하는 방식입니다. 정사각행렬이 아닌 경우에는 행렬식을 계산할 수 없습니다. 행렬식으로 계산하면 벡터와 행렬 간의 dot product를 통해 선형 변환한 결과의 부피를 구할 수 있습니다. 또한 행렬식을 사용해서 연립방정식의 해를 구할 때도 사용합니다.<br><br>
https://ko.wikipedia.org/wiki/%ED%96%89%EB%A0%AC%EC%8B%9D

In [100]:
a = np.array([[3,1],[2,2]])

In [101]:
a

array([[3, 1],
       [2, 2]])

In [102]:
np.det(a)

AttributeError: module 'numpy' has no attribute 'det'

In [103]:
np.linalg.det(a)

4.000000000000001

In [104]:
np.allclose(4.0, np.linalg.det(a))

True

### - 행렬식

- 행렬이 차원이 커질 경우 행렬식을 구할 때는 소행렬식을 사용해서 행렬식을 구할 수 있습니다. 3행 3열의 배열을 소행렬식으로 계산하기 위해 첫 번째 행을 제외하고 나머지 두 개의 행을 2행 2열로 만들어서 소행렬식을 구하고 첫 번째 행의 값을 곱한 후에 부호를 조정하면 행렬식 계산과 같습니다

$
\operatorname{det}\left[\begin{array}{lll}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{array}\right]
$
$
 =a_{11} \text { det }\left[\begin{array}{ll}
a_{22} & a_{23} \\
a_{32} & a_{33}
\end{array}\right]-a_{12} \text { det }\left[\begin{array}{ll}
a_{21} & a_{23} \\
a_{31} & a_{33}
\end{array}\right]+a_{13} \text { det }\left[\begin{array}{ll}
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{array}\right]
$

In [105]:
b = np.array([[3,1,3],[2,2,3],[1,1,1]])

In [106]:
b

array([[3, 1, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [107]:
3 * np.linalg.det(b[1:, 1:])

-3.0

In [108]:
np.linalg.det(b[1:, ::2]) #########################

-1.0

In [109]:
np.linalg.det(b[1:, :2])

0.0

In [110]:
np.linalg.det(b)

-2.0

In [111]:

-3 + 1 + 0

-2

### - 역행렬 (Inverse Matrix)

- 역행렬을 구할 때 행렬식의 결과값으로 나누는 것은 매우 중요합니다. 행렬식이 0이 나오면 수학적인 계산이 불가능해서 역행렬을 계산하지 못합니다.

$\begin{aligned} A^{-1}=& \frac{1}{a d-b c}\left[\begin{array}{cc}d & -b \\ -c & a\end{array}\right]=\left[\begin{array}{ccc}\frac{d}{a d-b c} & -\frac{b}{a d-b c} \\ -\frac{c}{a d-b c} & \frac{a}{a d-b c}\end{array}\right] \\ &=\frac{a d j A}{\operatorname{det} A} \end{aligned}$

In [112]:
a = np.array([[3,2],[6,4]])

In [113]:
a

array([[3, 2],
       [6, 4]])

In [114]:
np.linalg.det(a)

0.0

In [115]:
b = np.array([[1,2,3],[4,5,6],[3,2,4]])

In [116]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 4]])

In [117]:
np.linalg.det(b)

-9.000000000000002

In [118]:
bi = np.linalg.inv(b)

In [119]:
bi

array([[-0.88888889,  0.22222222,  0.33333333],
       [-0.22222222,  0.55555556, -0.66666667],
       [ 0.77777778, -0.44444444,  0.33333333]])

In [120]:
bb = np.dot(b, bi)

In [121]:
bb

array([[ 1.00000000e+00,  1.66533454e-16, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

In [122]:
a = np.eye(3)

In [123]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [124]:
np.allclose(np.eye(3), bb)

True

### - 역행렬의 교환법칙

- 역행렬의 행렬곱 연산은 반대로 계산해도 동일한 단위행렬이 나옵니다. 단위행렬은 보통 대문자 I로 사용하지만 대문자 E로도 표기하는 경우도 있습니다.

$
A^{-1}=A^{-1} A=E
$

In [125]:
a = np.array([[1,2],[3,4]])

In [126]:
a

array([[1, 2],
       [3, 4]])

In [127]:
ai = np.linalg.inv(a)

In [128]:
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [129]:
x = np.dot(a, ai)

In [130]:
x

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [131]:
b = np.eye(2)

In [132]:
b

array([[1., 0.],
       [0., 1.]])

In [133]:
np.allclose(b, x)

True

In [134]:
y = np.dot(ai, a)

In [135]:
y

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [136]:
np.allclose(np.eye(2), y)

True

### - 역행렬의 분배처리

- 두 행렬 A, B의 행렬곱을 하면 하나의 행렬이 만들어집니다. 이를 -1을 위 첨자로 사용해서 역행렬을 표시할 수 있습니다. 이 산식을 전개하면 두 행렬의 위치가 변경되고 각 행렬마다 위 첨자를 사용해서 역행렬을 표시합니다.

$
(A B)^{-1}=B^{-1} A^{-1}
$

In [137]:
a = np.array([[1,2],[3,4]])

In [138]:
a

array([[1, 2],
       [3, 4]])

In [139]:
np.linalg.det(a)

-2.0000000000000004

In [140]:
b = np.array([[3,4],[1,2]])

In [141]:
b

array([[3, 4],
       [1, 2]])

In [142]:
np.linalg.det(b)

2.0000000000000004

In [143]:
ai = np.linalg.inv(a)

In [144]:
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [145]:
bi = np.linalg.inv(b)

In [146]:
bi

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [147]:
ab = np.linalg.inv(np.dot(a, b))

In [148]:
ab

array([[-5.  ,  2.  ],
       [ 3.25, -1.25]])

In [149]:
ba = np.dot(bi, ai)

In [150]:
ba

array([[-5.  ,  2.  ],
       [ 3.25, -1.25]])

In [151]:
np.allclose(ab,ba)

True

### - 의사 역행렬

- 역행렬은 정사각행렬 중에 행렬식이 0이 아닌 경우에만 구할 수 있습니다. 특정 행렬이 역행렬이 없을 떄에 역행렬을 임의로 계산하는 것을 의사 역행렬이라고 합니다.

In [152]:
a = np.ones((3,3))

In [153]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [154]:
np.linalg.det(a)

0.0

In [155]:
np.linalg.pinv(a)

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [156]:
try : np.linalg.inv(a)
except Exception as e: print(e)

Singular matrix


## einsum 연산 확인하기

### 전치행렬

- 아인슈타인의 합은 선형대수학을 물리학에 응용하면서 좌표계에 관한 공식을 다룰 때 유용한 표기규칙으로 선형대수를 편리하게 계산할 수 있는 방법입니다.
- 전치행렬을 처리하려면 먼저 문자열에 두 행렬의 인덱스 정보를 반대로 만듭니다. 

In [157]:
a = np.array([[1,2,3],[4,5,6]])

In [158]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [160]:
np.einsum("ij->ji", a)

array([[1, 4],
       [2, 5],
       [3, 6]])

### 하나의 벡터와 행렬 계산

- Einsum으로 벡터의 원소를 합산할 경우는 하나의 인덱스를 표시하고 결과는 아무것도 표시하지 않습니다. 
- 벡터는 하나, 행렬은 두 개의 인덱스를 문자로 표시해야합니다. 

In [161]:
aa = np.arange(10)

In [162]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
a = np.einsum('i->', aa)

In [164]:
a

45

In [165]:
b = np.sum(aa)

In [166]:
b

45

In [167]:
a__ = np.array([[1,1,1],[3,2,4],[7,5,8]])

In [168]:
a__

array([[1, 1, 1],
       [3, 2, 4],
       [7, 5, 8]])

In [169]:
__a = np.einsum("ij->", a__)

In [170]:
__a

32

In [171]:
__a = np.sum(a__)

In [172]:
__a

32

__행렬 축에 따른 계산__

In [173]:
a = np.einsum("ij->i", a__)

In [174]:
a

array([ 3,  9, 20])

In [175]:
a = np.sum(a__, axis=1)

In [176]:
a

array([ 3,  9, 20])

In [177]:
a = np.einsum("ij->j", a__)

In [178]:
a

array([11,  8, 13])

In [179]:
a = np.sum(a__, axis=0)

In [180]:
a

array([11,  8, 13])

### 두 개의 배열 연산

- 두 개의 1차원 배열을 가지고 곱셈과 닷연산은 동일한 인덱스 문자를 사용합니다.

In [181]:
c = np.arange(10)

In [182]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
d = np.arange(5, 15)

In [184]:
d

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

__두 벡터의 곱셈__

In [185]:
a = np.einsum('i,i->i', c, d)

In [186]:
a

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [187]:
a = np.einsum('i,i->', c, d)

In [188]:
a

510

In [189]:
a = np.dot(c,d)

In [190]:
a

510

### 행벡터와 열벡터의 닷연산

- 두 개의 벡터를 행벡터와 열벡터의 닷연산으로 계산이 가능합니다.

In [191]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
d

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [193]:
c_ = c.reshape(10,1)

In [194]:
d_ = d.reshape(1,10)

In [195]:
c_

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [196]:
d_

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [197]:
np.dot(c_,d_)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [198]:
np.einsum('i,j->ij', c,d)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [199]:
np.outer(c,d)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

### 행렬 einnum 연산

- 두 개의 2차원 배열을 인자로 받아서 행렬의 곱셈, 닷연산을 einsum 함수로 계산합니다.

In [200]:
e = np.arange(10).reshape(2,5)

In [201]:
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [202]:
f = np.arange(5, 15).reshape(2,5)

In [203]:
f

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

__행렬의 곱셈__

In [204]:
np.einsum('ij,ij->ij', e, f)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

__행렬의 닷연산__

In [205]:
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [206]:
f_ = f.T

In [207]:
f_

array([[ 5, 10],
       [ 6, 11],
       [ 7, 12],
       [ 8, 13],
       [ 9, 14]])

In [208]:
np.einsum('ij,jk->ik', e,f.T)

array([[ 80, 130],
       [255, 430]])

In [209]:
np.dot(e,f.T)

array([[ 80, 130],
       [255, 430]])

# chapter 4 끝