In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## einsum 

    https://stackoverflow.com/questions/26089893/understanding-numpys-einsum
    
    https://ita9naiwa.github.io/numeric%20calculation/2018/11/10/Einsum.html

In [3]:
np.einsum

<function numpy.einsum(*operands, **kwargs)>

## 예제 4-6-2-1  두개 배열의 연산 처리하기

###  두개의 배열 곱하기 

In [4]:
C = np.arange(10)

In [5]:
D = np.arange(5, 15)

In [6]:
np.einsum('i,i->i', C, D)

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [7]:
np.einsum('i,i->', C, D)

510

In [8]:
np.dot(C,D)

510

In [9]:
np.einsum('i,j->i', C, D)

array([  0,  95, 190, 285, 380, 475, 570, 665, 760, 855])

In [10]:
C.reshape(10,1).repeat(10,axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [11]:
np.dot(C.reshape(10,1).repeat(10,axis=1), D.reshape(10,1)).T[0]

array([  0,  95, 190, 285, 380, 475, 570, 665, 760, 855])

In [12]:
np.einsum('i,j->j', C, D)

array([225, 270, 315, 360, 405, 450, 495, 540, 585, 630])

In [13]:
D.reshape(1,10).repeat(10,axis=0)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [14]:
np.dot(C.reshape(1,10), D.reshape(1,10).repeat(10,axis=0))[0]

array([225, 270, 315, 360, 405, 450, 495, 540, 585, 630])

### outer 연산하기

In [15]:
np.einsum('i,j->ij', C, D)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [16]:
np.outer(C, D)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [17]:
np.dot(C.reshape(10,1), D.reshape(1,10))

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

In [18]:
np.einsum('i,j->ji', C, D)

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99],
       [  0,  12,  24,  36,  48,  60,  72,  84,  96, 108],
       [  0,  13,  26,  39,  52,  65,  78,  91, 104, 117],
       [  0,  14,  28,  42,  56,  70,  84,  98, 112, 126]])

In [19]:
np.outer(D.reshape(10,1), C.reshape(1,10))

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99],
       [  0,  12,  24,  36,  48,  60,  72,  84,  96, 108],
       [  0,  13,  26,  39,  52,  65,  78,  91, 104, 117],
       [  0,  14,  28,  42,  56,  70,  84,  98, 112, 126]])