In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-2-1-1  브로드캐스팅 내장클래스  이용

In [3]:
x = np.arange(10).reshape(2,5)

In [4]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
y = np.arange(5)

In [6]:
y

array([0, 1, 2, 3, 4])

In [7]:
np.broadcast

numpy.broadcast

In [8]:
type(np.broadcast)

type

In [9]:
z = np.broadcast(x,y)

In [10]:
z

In [11]:
type(z)

numpy.broadcast

In [12]:
z.shape, z.ndim

((2, 5), 2)

In [13]:
for i in z :
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [14]:
z = np.broadcast(x,y)

In [15]:
b = np.empty(z.shape,int)

In [16]:
b.flat

In [17]:
b.flat =  [ i for _,i in z]

In [18]:
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [19]:
x + b

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [20]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

## 예제 4-2-1-2  브로드캐스팅 내장함수 이용

In [21]:
a = np.array([1,2,3])

In [22]:
ax = np.broadcast_to(a,(3,3))

In [23]:
ax

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [24]:
try :
    np.broadcast_to(a,(3,4))
except Exception as e :
    print(e)

operands could not be broadcast together with remapped shapes [original->remapped]: (3,) and requested shape (3,4)


In [25]:
a = np.broadcast_arrays(np.array([1,2,3,4]), np.array([5,6,7,8]))

In [26]:
a

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [27]:
b = np.broadcast_arrays(np.array([1,2,3,4]), np.array([[5,6,7,8],[7,8,9,10]]))

In [28]:
b

[array([[1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 7,  8,  9, 10]])]

In [29]:
try :
    c = np.broadcast_arrays(np.array([1,2,3,4]), np.array([[5,6,7],[7,8,9]]))
except Exception as e :
    print(e)

shape mismatch: objects cannot be broadcast to a single shape


In [30]:
 c = np.broadcast_arrays(np.arange(3).reshape(1,3),
                         np.arange(3).reshape(3,1),)

In [31]:
c

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])]

## 예제 4-2-1-3 브로드캐스팅 규칙 이해하기

In [32]:
x2 = np.ones((2,3))

In [33]:
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
x1 = np.ones(3)

In [35]:
x1

array([1., 1., 1.])

In [36]:
x1.shape, x2.shape

((3,), (2, 3))

In [37]:
x1.shape[0] == x2.shape[1]

True

In [38]:
x1 = x1[np.newaxis,]

In [39]:
x1.shape

(1, 3)

In [40]:
x1 = np.vstack((x1[0],x1[0]))

In [41]:
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
x1.shape ==  x2.shape

True

In [43]:
x1 + x2

array([[2., 2., 2.],
       [2., 2., 2.]])