In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-1-1-1  벡터간의 덧셈

In [3]:
d = np.array([3,4])

In [4]:
e = np.array([5,6])

In [5]:
d + e

array([ 8, 10])

In [6]:
np.add(d, e)

array([ 8, 10])

In [7]:
f = np.array([1,2,3])

In [8]:
try :
    f + e
except Exception as ex :
    print(ex)

operands could not be broadcast together with shapes (3,) (2,) 


## 예제 4-1-1-2  벡터간의 뺄셈

In [9]:
d = np.array([3,4])

In [10]:
e = np.array([5,6])

In [11]:
d - e

array([-2, -2])

In [12]:
np.subtract(d,e)

array([-2, -2])

In [13]:
d + (-e)

array([-2, -2])

In [14]:
np.add(d, np.negative(e))

array([-2, -2])

## 예제 4-1-1-3  스칼라 값을 벡터에 곱하기

In [15]:
d = np.array([2,3])

In [16]:
3 * d

array([6, 9])

In [17]:
np.array([3,3]) * d

array([6, 9])

In [18]:
np.multiply(3, d)

array([6, 9])

In [19]:
np.multiply(np.array([3,3]), d)

array([6, 9])

In [20]:
1/3 * d

array([0.66666667, 1.        ])

In [21]:
np.divide(d,3)

array([0.66666667, 1.        ])

In [22]:
np.multiply(d, (1/3))

array([0.66666667, 1.        ])