In [1]:
import numpy as np

In [2]:
np.kron

<function numpy.kron(a, b)>

## 두 배열의 형상의 곱만큼 원소가 증가

In [4]:
np.kron([1,2,3], [10,20,30])

array([10, 20, 30, 20, 40, 60, 30, 60, 90])

In [5]:
x = np.array([1,2,3,4]).reshape(2,2)

In [10]:
x

array([[1, 2],
       [3, 4]])

In [6]:
y = np.eye(2)

In [9]:
y

array([[1., 0.],
       [0., 1.]])

In [8]:
np.kron(y,x)

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 3., 4.]])

## einsum 

    https://stackoverflow.com/questions/26089893/understanding-numpys-einsum

In [3]:
np.einsum

<function numpy.einsum(*operands, **kwargs)>

In [108]:
A_ = np.array([0, 1, 2])

B_ = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [112]:
A_[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [113]:
A_[:, np.newaxis] * B_

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [110]:
(A_[:, np.newaxis] * B_).sum(axis=1)

array([ 0, 22, 76])

In [115]:
np.einsum('i,ij->', A_, B_)

98

In [111]:
np.einsum('i,ij->i', A_, B_)

array([ 0, 22, 76])

In [118]:
(A_[:, np.newaxis] * B_).sum(axis=0)

array([20, 23, 26, 29])

In [117]:
np.einsum('i,ij->j', A_, B_)

array([20, 23, 26, 29])

In [125]:
A__ = np.array([[1, 1, 1],
           [3, 2, 4],
           [7, 5, 8]])


In [126]:
B__ = np.array([[0, 1, 0],
           [1, 1, 0],
           [1, 1, 1]])

### 대각선의 합과 대각선의 성분

In [127]:
np.einsum("ii ->", A__)

11

In [128]:
np.einsum("ii ->i", A__)

array([1, 2, 8])

In [130]:
np.einsum("ij->", A__)

32

In [131]:
np.sum(A__)

32

### 수평축으로 계산하기 

In [132]:
np.einsum("ij->i", A__)

array([ 3,  9, 20])

In [134]:
np.sum(A__, axis=1)

array([ 3,  9, 20])

### 수직축으로 계산하기 

In [136]:
np.einsum("ij->j", A__)

array([11,  8, 13])

In [135]:
np.sum(A__, axis=0)

array([11,  8, 13])

### 모든 원소 더하기

In [69]:
AA = np.arange(10)

In [91]:
BB = np.arange(5, 15)

In [70]:
np.einsum('i->', AA)

45

In [74]:
np.sum(AA)

45

In [71]:
A = np.array([[1,2,3], [4,5,6]])

In [72]:
np.einsum('ij->', A)

21

In [75]:
np.sum(A)

21

###  두개의 배열 곱하기 

In [84]:
C = np.arange(10)

In [85]:
D = np.arange(5, 15)

In [86]:
np.einsum('i,i->i', C, D)

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [87]:
E = np.arange(10).reshape(2,5)

In [88]:
F = np.arange(5, 15).reshape(2,5)

In [90]:
np.einsum('ij,ij->ij', E, F)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

###  대각선 성분합 구하기

In [79]:
AB = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [80]:
trace =np.einsum('ii->', AB)
print(trace)

15


In [100]:
np.einsum('ii', AB)

15

In [82]:
np.trace(AB)

15

### 전치행렬 만들기 

In [76]:
R = np.einsum("ij->ji", A)

In [77]:
R

array([[1, 4],
       [2, 5],
       [3, 6]])

##  닷연산 구하기

In [97]:
np.einsum('i,i->', C, D)

510

In [98]:
np.dot(C,D)

510

### 전치 행렬 변환 후 곱하기

In [102]:
x

array([[1, 2],
       [3, 4]])

In [106]:
x.T

array([[1, 3],
       [2, 4]])

In [105]:
np.einsum('ij,ji->ij', x,x)

array([[ 1,  6],
       [ 6, 16]])

In [107]:
x * x.T

array([[ 1,  6],
       [ 6, 16]])

### 2차원 닷 연산 구하기

In [34]:
np.einsum('ij,jk->ik', x,y)

array([[1., 2.],
       [3., 4.]])

In [35]:
np.dot(x,y)

array([[1., 2.],
       [3., 4.]])

In [42]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)*2
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


###  아웃터 

In [99]:
np.einsum('i,j->ij', C, D)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

### 첫번째 행렬의 행을 기준으로 sum(aij*bji)

In [48]:
np.einsum("ij,jk->i",a,b)

array([ 46, 136])

In [54]:
np.dot(a[0], b[:,0]) + np.dot(a[0], b[:,1])

46

In [55]:
np.dot(a[1], b[:,0]) + np.dot(a[1], b[:,1])

136

### 두 번째 행렬의 열을 기준으로 sum(bij*aji)

In [47]:
np.einsum("ij,jk->k",a,b)

array([ 76, 106])

In [64]:
b.T

array([[ 0,  4,  8],
       [ 2,  6, 10]])

In [65]:
np.dot(b.T[0], a[0]) + np.dot(b.T[0], a[1]) 

76

In [66]:
np.dot(b.T[1], a[0]) + np.dot(b.T[1], a[1]) 

106

### 닷연산

In [49]:
np.einsum("ij,jk->ik",a,b)

array([[20, 26],
       [56, 80]])

In [44]:
np.dot(a,b)

array([[20, 26],
       [56, 80]])