In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## einsum 

    https://stackoverflow.com/questions/26089893/understanding-numpys-einsum
    
    https://ita9naiwa.github.io/numeric%20calculation/2018/11/10/Einsum.html

## 예제 4-6-1-1 하나 배열의 연산 처리하기

In [3]:
np.einsum

<function numpy.einsum(*operands, **kwargs)>

In [4]:
A = np.array([[1,2,3], [4,5,6]])

In [5]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
np.einsum("ij->ji", A)

array([[1, 4],
       [2, 5],
       [3, 6]])

### 전체 원소의 합

In [8]:
AA = np.arange(10)

In [9]:
np.einsum('i->', AA)

45

In [10]:
np.sum(AA)

45

In [11]:
A__ = np.array([[1, 1, 1],
           [3, 2, 4],
           [7, 5, 8]])


In [12]:
np.einsum("ij->", A__)

32

In [13]:
np.sum(A__)

32

### 수평축과 수직축으로 계산하기 

In [14]:
np.einsum("ij->i", A__)

array([ 3,  9, 20])

In [15]:
np.sum(A__, axis=1)

array([ 3,  9, 20])

In [16]:
np.einsum("ij->j", A__)

array([11,  8, 13])

In [17]:
np.sum(A__, axis=0)

array([11,  8, 13])

### 대각선의 합과 대각선의 성분

In [18]:
np.einsum("ii", A__)

11

In [19]:
np.einsum("ii ->", A__)

11

In [20]:
np.trace(A__)

11

In [21]:
np.einsum("ii ->i", A__)

array([1, 2, 8])

In [22]:
np.diag(A__)

array([1, 2, 8])