In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-4-4-1 소행렬식

In [3]:
ma  = np.arange(1,10).reshape(3,3)

In [4]:
ma

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
list(range(0))

[]

In [6]:
a = np.array(list(range(0)) + list(range(1,3)))[:,np.newaxis]

In [7]:
a

array([[1],
       [2]])

In [8]:
b = np.array(list(range(0)) + list(range(1,3)))

In [9]:
b

array([1, 2])

In [10]:
ja = ma[a,b]

In [11]:
ja

array([[5, 6],
       [8, 9]])

In [12]:
np.linalg.det(ja)

-2.9999999999999996

## 예제 4-4-4-2   여인수 알아보기

In [13]:
cofactor = (-1)**(0+0) * np.linalg.det(ja)

In [14]:
cofactor

-2.9999999999999996