In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-5-3-1  텐서 더블 컨트랙트

In [3]:
x = np.random.randint(1,10,(2,2))

In [4]:
x

array([[7, 4],
       [3, 5]])

In [5]:
y = np.random.randint(1,10,(2,2))

In [6]:
y

array([[4, 4],
       [8, 7]])

In [7]:
a = np.tensordot(x,y, axes=2)

In [8]:
a.shape

()

In [9]:
a

array(103)

In [10]:
c = np.random.randint(1,10,(2,2,2))

In [11]:
c

array([[[4, 1],
        [3, 5]],

       [[9, 7],
        [9, 4]]])

In [12]:
d = np.random.randint(1,10,(2,2,2))

In [13]:
d

array([[[4, 9],
        [3, 6]],

       [[6, 3],
        [7, 8]]])

In [14]:
np.dot(c.reshape(2,4), d.reshape(4,2))

array([[ 72,  91],
       [139, 182]])

In [15]:
b = np.tensordot(c,d, axes=2)

In [16]:
b

array([[ 72,  91],
       [139, 182]])