In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-2-3-1  스칼라에 대한 확장 처리  

In [3]:
x = np.ones((2,3))

In [4]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
y = np.array(10)

In [6]:
y

array(10)

In [7]:
x.shape, y.shape

((2, 3), ())

In [8]:
y = y[np.newaxis]

In [9]:
y

array([10])

In [10]:
y.shape

(1,)

In [11]:
y = y[np.newaxis, :]

In [12]:
y

array([[10]])

In [13]:
y.shape

(1, 1)

In [14]:
y = np.broadcast_to(y,(2,3))

In [15]:
y

array([[10, 10, 10],
       [10, 10, 10]])

In [16]:
x+y

array([[11., 11., 11.],
       [11., 11., 11.]])

In [17]:
10 + x

array([[11., 11., 11.],
       [11., 11., 11.]])