In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## einsum 

    https://stackoverflow.com/questions/26089893/understanding-numpys-einsum
    
    https://ita9naiwa.github.io/numeric%20calculation/2018/11/10/Einsum.html

In [3]:
np.einsum

<function numpy.einsum(*operands, **kwargs)>

## 예제 4-6-3-1  두 개  2차원 배열의 연산 처리하기

In [4]:
E = np.arange(10).reshape(2,5)

In [5]:
F = np.arange(5, 15).reshape(2,5)

In [6]:
np.einsum('ij,ij->ij', E, F)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [7]:
np.einsum('ij,jk->ik', E, F.T)

array([[ 80, 130],
       [255, 430]])

In [8]:
np.dot(E, F.T)

array([[ 80, 130],
       [255, 430]])

### 두 배열의 곱연산 후에 축 별로 합산하기

In [9]:
A_ = np.array([0, 1, 2])

In [10]:
B_ = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [11]:
np.einsum('i,ij->', A_, B_)

98

In [12]:
np.sum(A_) + np.sum(B_)

69

In [13]:
(A_.reshape(3,1) * B_).sum()

98

In [14]:
A_[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [15]:
A_[:, np.newaxis] * B_

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [16]:
(A_[:, np.newaxis] * B_).sum()

98

In [17]:
np.einsum('i,ij->i', A_, B_)

array([ 0, 22, 76])

In [18]:
(A_[:, np.newaxis] * B_).sum(axis=1)

array([ 0, 22, 76])

In [19]:
np.einsum('i,ij->j', A_, B_)

array([20, 23, 26, 29])

In [20]:
(A_[:, np.newaxis] * B_).sum(axis=0)

array([20, 23, 26, 29])

### 전치 행렬 변환 후 곱하기

In [21]:
x = np.array([1,2,3,4]).reshape(2,2)

In [22]:
x.T

array([[1, 3],
       [2, 4]])

In [23]:
try :
    np.einsum('ii,ii->ii', x,x)
except Exception as e :
    print(e)

einstein sum subscripts string includes output subscript 'i' multiple times


In [24]:
np.einsum('ij,ij->ij', x,x)

array([[ 1,  4],
       [ 9, 16]])

In [25]:
x * x

array([[ 1,  4],
       [ 9, 16]])

In [26]:
np.einsum('ij,ji->ij', x,x)

array([[ 1,  6],
       [ 6, 16]])

In [27]:
x * x.T

array([[ 1,  6],
       [ 6, 16]])

In [28]:
np.einsum('ij,jk->ik', x,x.T)

array([[ 5, 11],
       [11, 25]])

In [29]:
np.dot(x ,x.T)

array([[ 5, 11],
       [11, 25]])

### 첫번째 행렬의 행을 기준으로 sum(aij*bji)

In [30]:
x = np.array([1,3,4,2]).reshape(2,2)

In [31]:
y = np.array([1,2,4,2]).reshape(2,2)

In [32]:
np.dot(x,y)

array([[13,  8],
       [12, 12]])

In [33]:
np.dot(x,y).sum(axis=1)

array([21, 24])

In [34]:
np.einsum("ij,jk->i",x,y)

array([21, 24])

In [35]:
np.dot(x[0], y[:,0]) + np.dot(x[0], y[:,1])

21

In [36]:
np.dot(x[1], y[:,0]) + np.dot(x[1], y[:,1])

24

### 두 번째 행렬의 열을 기준으로 sum(bkj*aji)

In [37]:
np.dot(x,y).sum(axis=0)

array([25, 20])

In [38]:
np.einsum("ij,jk->k",x,y)

array([25, 20])

In [39]:
y.T

array([[1, 4],
       [2, 2]])

In [40]:
np.dot(y.T[0], x[0]) + np.dot(y.T[0], x[1]) 

25

In [41]:
np.dot(y.T[1], x[0]) + np.dot(y.T[1], x[1]) 

20