In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-3-1-1  벡터의 내적 이해하기

In [3]:
a = np.array([3,4])

In [4]:
b = np.array([5,6])

In [5]:
a @ b

39

In [6]:
np.dot(a,b)

39

In [7]:
np.inner(a,b)

39

## 예제 4-3-1-2  벡터의 외적 이해하기

In [8]:
a = np.array([1,4])

In [9]:
b = np.array([3,6])

In [10]:
np.cross(a,b)

array(-6)

In [11]:
c = np.array([1,4,3])

In [12]:
d = np.array([3,4,5])

In [13]:
np.cross(c,d)

array([ 8,  4, -8])

In [14]:
np.outer(a,b)

array([[ 3,  6],
       [12, 24]])

In [15]:
np.outer(c,d)

array([[ 3,  4,  5],
       [12, 16, 20],
       [ 9, 12, 15]])