In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 4-2-2-1  랭크가 다른 경우 

In [3]:
x = np.arange(1,7).reshape(2,3)

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y = np.arange(1,4)

In [6]:
y

array([1, 2, 3])

In [7]:
x.ndim > y.ndim

True

In [8]:
np.linalg.matrix_rank(x)

2

In [9]:
np.linalg.matrix_rank(y)

1

In [10]:
z = np.broadcast_arrays(x,y)

In [11]:
z

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [1, 2, 3]])]

In [12]:
z[0] + z[1]

array([[2, 4, 6],
       [5, 7, 9]])

In [13]:
x + y 

array([[2, 4, 6],
       [5, 7, 9]])

## 예제 4-2-2-2  배열 내부 모양에서 1이 존재

In [14]:
x = np.arange(1,5).reshape(2,2)

In [15]:
x

array([[1, 2],
       [3, 4]])

In [16]:
y = np.arange(1,3).reshape(1,2)

In [17]:
y

array([[1, 2]])

In [18]:
z = np.broadcast_arrays(x,y)

In [19]:
z[0].shape == z[1].shape

True

In [20]:
z

[array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [1, 2]])]

In [21]:
b = np.arange(1,3).reshape(2,1)

In [22]:
b

array([[1],
       [2]])

In [23]:
zb = np.broadcast_arrays(x,b) 


In [24]:
zb

[array([[1, 2],
        [3, 4]]),
 array([[1, 1],
        [2, 2]])]