In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

## 예제 9-1-3-1  원소 섞어서 처리하기

In [11]:
a = np.random.choice(5,3,p=[0.1,0.2,0.2,0.2,0.3])

In [12]:
a

array([3, 1, 1], dtype=int64)

In [13]:
np.random.shuffle(a)

In [14]:
a

array([1, 1, 3], dtype=int64)

In [15]:
np.random.permutation(a)

array([1, 3, 1], dtype=int64)

In [16]:
b = np.arange(9).reshape(3,3)

In [17]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.random.permutation(b)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
np.random.shuffle(b)

In [20]:
b

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 예제 9-1-3-2  난수 발생 재현하기

In [30]:
np.random.seed(100)
a = np.random.rand(5)
b = np.random.rand(5)

In [31]:
a

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [32]:
b

array([0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [36]:
np.random.seed(100)
c = np.random.rand(5)
d = np.random.rand(5)
e = np.random.rand(5)

In [34]:
c

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [35]:
d

array([0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [37]:
e

array([0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749])