In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

## 예제 9-2-2-1  범위와 백분위 알아보기

In [3]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

In [4]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [11]:
np.max(a), np.min(a)

(9, 2)

In [12]:
np.max(a)- np.min(a)

7

In [13]:
np.ptp(a)

7

In [16]:
np.max(a, axis=0)- np.min(a, axis=0)

array([6, 3, 6])

In [14]:
np.ptp(a, axis=0)

array([6, 3, 6])

In [17]:
np.max(a, axis=1)- np.min(a, axis=1)

array([4, 5, 7])

In [18]:
np.ptp(a, axis=1)

array([4, 5, 7])

In [26]:
b = np.array([[30,70,50],[80,40,30],[20,40,90]])

In [27]:
c = b.flatten()

In [29]:
c.sort()

In [30]:
c

array([20, 30, 30, 40, 40, 50, 70, 80, 90])

In [31]:
np.percentile(a, 50)

40.0

In [33]:
np.percentile(a, 50, axis=0)

array([30., 40., 50.])

In [34]:
np.percentile(a, 50, axis=1)

array([50., 40., 40.])

## 예제 9-2-2-2  중앙값과 평균 알아보기 

In [35]:
d = np.array([3,4,2,3,8,9,5])

In [36]:
np.median(d)

4.0

In [37]:
np.sort(d)

array([2, 3, 3, 4, 5, 8, 9])

In [38]:
e = np.array([3,4,2,3,8,9,5,7])

In [39]:
np.median(e)

4.5

In [40]:
np.sort(e)

array([2, 3, 3, 4, 5, 7, 8, 9])

In [41]:
d.mean()

4.857142857142857

In [43]:
np.mean(d)

4.857142857142857

In [44]:
np.average(d)

4.857142857142857

In [45]:
f = np.reshape(e, (4,2))

In [46]:
np.mean(f, axis=0)

array([4.5 , 5.75])

In [47]:
np.mean(f, axis=1)

array([3.5, 2.5, 8.5, 6. ])