In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

### 방정식 
     
    3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

In [3]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)

In [4]:
x

array([2., 3.])

In [5]:
np.allclose(np.dot(a, x), b)

True

In [20]:
A = np.array( [[1,0,0],
    [1,1,1],
    [6,7,0]])
b =np.array([0,24,0])

In [21]:
x = np.dot(np.linalg.inv(A), b) 

In [22]:
x

array([ 0.,  0., 24.])

In [24]:
np.allclose(np.dot(A, x), b)

True

###  lstsq

lstsq 명령은 행렬  𝐴
 와  𝑏  모두 인수로 받고 뒤에서 설명할 최소자승문제(least square problem)의 답 x, 잔차제곱합(residual sum of squares) resid, 랭크(rank) rank, 특잇값(singular value) s를 반환한다. 미지수와 방정식의 개수가 같고 행렬  𝐴의 역행렬이 존재하면 최소자승문제의 답과 선형 연립방정식의 답이 같으므로 lstsq 명령으로 선형 연립방정식을 풀 수도 있다. 최소자승문제, 랭크, 특잇값에 대해서는 뒤에서 자세히 설명할 것이다.


lstsq 명령을 사용하는 것이 inv 명령을 사용하는 것보다 수치오차가 적고 코드도 간단하므로 선형 연립방정식의 해를 구할 때도 lstsq 명령을 사용하는 것을 권장한다.

In [30]:
A = np.array([[1,0,0],[1,4,1],[0,0,1]])
b = np.array([0,24,0])

In [39]:
np.linalg.matrix_rank(A)

3

In [31]:
x = np.linalg.lstsq(A,b, rcond=-1)

In [32]:
x

(array([-5.72756867e-15,  6.00000000e+00,  8.88178420e-16]),
 array([], dtype=float64),
 3,
 array([4.25638861, 1.        , 0.93976382]))

In [33]:
np.allclose(np.dot(A, x[0]), b)

True

### 

stsq 명령을 사용하는 것이 inv 명령을 사용하는 것보다 수치오차가 적고 코드도 간단하므로 선형 연립방정식의 해를 구할 때도 lstsq 명령을 사용하는 것을 권장한다.

In [35]:
x_ = np.dot(np.linalg.inv(A), b) 

In [37]:
x[0] - x_

array([-5.72756867e-15,  5.32907052e-15,  8.88178420e-16])

In [51]:
x, resid, rank, s = np.linalg.lstsq(A, b, rcond=-1)

In [42]:
x

array([-5.72756867e-15,  6.00000000e+00,  8.88178420e-16])

### resid는 잔차벡터의  𝑒=𝐴𝑥−𝑏 의 제곱합, 즉 놈의 제곱이다

In [47]:
np.linalg.norm(A @ x - b) ** 2

2.3554229553999296e-28

In [48]:
np.allclose(np.linalg.norm(A @ x - b) ** 2, 0)

True

In [43]:
resid

array([], dtype=float64)

In [44]:
rank

3

### 특이값분해(singular value decomposition;svd)에 

https://blog.naver.com/cjh226/220861349129

https://darkpgmr.tistory.com/106

In [50]:
u, s_, vh = np.linalg.svd(A, full_matrices=True)

In [52]:
s_

array([4.25638861, 1.        , 0.93976382])

In [53]:
s

array([4.25638861, 1.        , 0.93976382])

In [9]:
A = np.random.random((3, 3))
b = np.random.random(3)

In [15]:
A

array([[0.04240525, 0.71949305, 0.43071277],
       [0.50507005, 0.94110972, 0.23497262],
       [0.97650567, 0.40472616, 0.02678486]])

In [16]:
b

array([0.81334702, 0.37887035, 0.18090484])

In [11]:
x =  np.linalg.solve(A, b)

In [12]:
x

array([ 0.26287915, -0.34914095,  2.44572282])

In [13]:
np.dot(A, x) - b

array([3.33066907e-16, 1.11022302e-16, 2.77555756e-17])

In [18]:
np.allclose(np.dot(A, x), b)

True