In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

# chapter 5. 다차원 배열의 구조 변경하기

## 변경 및 결합 주요 함수

### 배열의 형상 변경

- 1차원 배열을 만들고 내부의 원소 개수가 동일한 형상을 가진 다른 차원의 배열로 변경할 수 있습니다.
- Reshape 메소드에 형상을 인자로 전달해서 배열의 형상을 변경합니다.

In [5]:
x = np.arange(16)

In [6]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
x1 = x.reshape(2,8)

In [8]:
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

__원소의 개수가 안 맞으면 에러 발생__

In [11]:
try:
    x2 = x.reshape(4,5)
except Exception as e:
    print (e)

cannot reshape array of size 16 into shape (4,5)


__-1을 지정하면 나머지 형상이 자동으로 세팅됨__

In [12]:
y1 = x.reshape(4,-1)

In [14]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
y2 = x.reshape(8,-1)

In [16]:
y2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

### 배열의 크기 변경

- 배열의 크기는 resize로 변경해봅니다. reshape와 차이점은 __더 큰 배열로 확장할 수 있다는 것__입니다.

__동일 차원에서 크기만 확장__

In [17]:
a = np.arange(4)

In [18]:
a

array([0, 1, 2, 3])

In [24]:
b = np.resize(a,8)

In [25]:
b

array([0, 1, 2, 3, 0, 1, 2, 3])

In [26]:
a

array([0, 1, 2, 3])

In [33]:
np.resize(a,9)

array([0, 1, 2, 3, 0, 1, 2, 3, 0])

In [34]:
np.resize(a,9)

array([0, 1, 2, 3, 0, 1, 2, 3, 0])

In [35]:
np.append(a,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

__shape를 다른 차원으로 확대 가능__

In [36]:
b = np.arange(4)

In [37]:
b

array([0, 1, 2, 3])

In [49]:
np.resize(b,(4,4)) 
########### [0,1,2,3],[0,0,0,0],[0,0,0,0],[0,0,0,0] 나오게 하려면

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [48]:
np.reshape(b,(4,4))

ValueError: cannot reshape array of size 4 into shape (4,4)

__새로운 배열을 만들 때 refcheck=False 지정__

In [51]:
c = np.arange(8)

In [52]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
c.resize(4, refcheck=False) # 구글링 결과 refcheck는 resize에만 해당

In [54]:
c

array([0, 1, 2, 3])

In [56]:
x = np.arange(16)

In [57]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
x.reshape((2,8),refcheck=False)

TypeError: 'refcheck' is an invalid keyword argument for this function

### 1차원 배열을 2차원 배열로 변경(1)

- Meshgrid 함수를 이용하면 두 개의 배열을 가지고 확장된 두 개의 다른 배열을 만듭니다.

In [95]:
x = np.arange(3)

In [96]:
x

array([0, 1, 2])

In [97]:
y = np.arange(4)

In [98]:
y

array([0, 1, 2, 3])

In [99]:
x_, y_ = np.meshgrid(x,y)

# x, y에 포함된 좌표를 바탕으로 좌표를 반환.
# x_는 각 행이 x의 복사본인 행렬
# y_는 각 열이 y의 복사본인 행렬

In [100]:
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [101]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [102]:
x__, y__ = np.meshgrid(y,x)

In [103]:
x__

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [104]:
y__

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [105]:
x_1, x_2 = np.meshgrid(x,x)

In [106]:
x_1

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [107]:
x_2

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [108]:
x_1 = x.reshape(1,-1)

In [109]:
x_1

array([[0, 1, 2]])

In [111]:
x_2 = np.concatenate([x_1,x_1])

In [112]:
x_2

array([[0, 1, 2],
       [0, 1, 2]])

In [123]:
x_3 = np.concatenate([x_1,x_2],axis=0)

In [124]:
x_3

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [116]:
y_1 = y.reshape(-1,1)

In [117]:
y_1

array([[0],
       [1],
       [2],
       [3]])

In [119]:
np.concatenate([y_1,y_1],axis=1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]])

### 1차원 배열을 2차원 배열로 변경 (2)

- mgrid 함수에 인자로 슬라이스를 전달하면 두 개의 배열을 반환합니다.

In [125]:
np.arange(10,30,10)

array([10, 20])

In [126]:
np.arange(1,5)

array([1, 2, 3, 4])

In [127]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1),np.arange(1,5).reshape(1,4)) ##########broadcast

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [130]:
np.broadcast_arrays(np.arange(1,5).reshape(1,4),np.arange(10,30,10).reshape(2,1))

[array([[1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[10, 10, 10, 10],
        [20, 20, 20, 20]])]

In [131]:
a,b = np.mgrid[10:30:10, 1:5]

In [132]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [133]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [138]:
a,b,c = np.mgrid[10:30:10, 1:5, 2:7]

In [139]:
a

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]]])

In [140]:
b

array([[[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]]])

In [141]:
c

array([[[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]],

       [[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]]])

### 1차원 배열을 2차원 배열로 변경 (3)

- ogird함수에 인자로 슬라이스 전달하면  2차원 두 개의 배열을 반환합니다.  첫번째는 열벡터이고 두번째는 행벡터입니다.  이 두개를 브로드캐스탱해서 동일한 형상의 배열을 만들 수 있습니다. 

In [8]:
c, d = np.ogrid[10:30:10,1:5]

In [9]:
c

array([[10],
       [20]])

In [10]:
d

array([[1, 2, 3, 4]])

In [11]:
e,f = np.broadcast_arrays(c,d)

In [12]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [13]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### 축이 1인 차원을 줄이기

- 다차원 배열에서 축의 차원이 1인 것을 없애서 차원을 축소할 필요가 있습니다. 이때 축소하는 함수 squeeze에 배열을 전달해서 사용합니다. 

In [32]:
x = np.array([[[0],[1],[2]]])
y = np.array([[0,1,2]])

In [33]:
x, y

(array([[[0],
         [1],
         [2]]]),
 array([[0, 1, 2]]))

In [34]:
x.shape, y.shape

((1, 3, 1), (1, 3))

In [41]:
x1 = np.squeeze(x)

In [44]:
x2 = np.squeeze(x, axis = 0)

In [45]:
x3 = np.squeeze(x, axis = 1)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [46]:
x4 = np.squeeze(x, axis = 2)

In [47]:
x, y, x1, x2, x4

(array([[[0],
         [1],
         [2]]]),
 array([[0, 1, 2]]),
 array([0, 1, 2]),
 array([[0],
        [1],
        [2]]),
 array([[0, 1, 2]]))

In [48]:
x1.shape, y.shape, x1.shape, x2.shape, x4.shape

((3,), (1, 3), (3,), (3, 1), (1, 3))

### 내부 원소를 가지고 배열 확대하기

- 원소를 반복해서 증가하는 repeat 함수, 주어진 배열의 크기를 확대하는 tile 함수등을 알아봅시다.

In [49]:
a = np.linspace(1,5,5, dtype=np.int32)

In [50]:
a

array([1, 2, 3, 4, 5], dtype=int32)

In [51]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int32)

In [52]:
np.repeat(a,a)

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5], dtype=int32)

In [53]:
e = np.arange(4)

In [54]:
e

array([0, 1, 2, 3])

In [55]:
e = np.arange(4).reshape(2,2)

In [56]:
e

array([[0, 1],
       [2, 3]])

In [57]:
np.tile(e,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [58]:
np.tile(e,3)

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3]])

### 배열을 결합하기

- 동일한 형상을 가진 두 개의 배열을 만들고 concatenate 함수로 수직과 수평으로 결합을 할 수 있습니다.

In [80]:
a = np.linspace(1,6,6, dtype=np.int32)

In [81]:
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [82]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [84]:
b = np.linspace(7,13,6, dtype=np.int32)

In [85]:
b

array([ 7,  8,  9, 10, 11, 13], dtype=int32)

In [86]:
b = np.linspace(7,13,6, dtype = np.int32).reshape(2,3)

In [87]:
b

array([[ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

__열의 크기가 동일할 때 수직 결합__

In [88]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [98]:
np.concatenate([a,b,a,b,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

__행의 크기가 동일할 때 수평 결합__

In [97]:
np.concatenate([a,b,a,b,b], axis = 1)

array([[ 1,  2,  3,  7,  8,  9,  1,  2,  3,  7,  8,  9,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13,  4,  5,  6, 10, 11, 13, 10, 11, 13]],
      dtype=int32)

__배열을 쌓기__

- 두 개의 ~~일차원~~배열을 만들고 stack, vstack, hstack 함수로 배열을 수직과 수평으로 쌓을 수가 있습니다.

In [99]:
x = np.array([1,2,3])

In [100]:
y = np.array([4,5,6])

In [101]:
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.stack([x,y], axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.stack([x,y], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [106]:
a = 0

In [107]:
a = np.vstack([x,y])

In [108]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.vstack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [110]:
np.stack([x,y], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [111]:
b = np.hstack([x,y])

In [112]:
b

array([1, 2, 3, 4, 5, 6])

In [119]:
x = np.array([[1,2,3,4,5,6]]).reshape(2,3)

In [122]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
y = np.array([[7,8,9,10,11,12]]).reshape(2,3)

In [120]:
b = np.hstack([x,y])

In [121]:
b

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [105]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### 배열을 분리하기 (np.split)

- 선형대수에서 큰 배열을 작은 배열로 분리해서 계산을 합니다. 넘파이 모듈의 다차원 배열도 하나의 배열을 분리해서 처리할 수 있습니다.

In [151]:
a = np.linspace(1,8,8, dtype=np.int32)

In [152]:
a

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [153]:
a = a.reshape(2,4)

In [154]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [155]:
b = np.linspace(9,16,8, dtype=np.int32)

In [156]:
b

array([ 9, 10, 11, 12, 13, 14, 15, 16], dtype=int32)

In [157]:
b = b.reshape(2,4)

In [158]:
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [159]:
c = np.vstack([a,b])

In [160]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [179]:
x,y = np.split(c, [2]) # ( , ) <---분리하고자 하는 위치 : 2번째 column 앞
# https://numpy.org/doc/stable/reference/generated/numpy.split.html

In [180]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [181]:
y 

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

### 배열 쌓기 객체

- 행과 열을 쌓을 때 r_, c_를 사용할 수도 있습니다.

In [182]:
a = np.arange(6).reshape(2,3)

In [183]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [184]:
c = np.random.randn(2,3)

In [185]:
c

array([[-0.08703845, -1.34217544,  0.33380794],
       [ 0.47838035,  0.6434542 ,  0.16241262]])

In [186]:
np.r_[a,c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [-0.08703845, -1.34217544,  0.33380794],
       [ 0.47838035,  0.6434542 ,  0.16241262]])

In [187]:
np.c_[a,c]

array([[ 0.        ,  1.        ,  2.        , -0.08703845, -1.34217544,
         0.33380794],
       [ 3.        ,  4.        ,  5.        ,  0.47838035,  0.6434542 ,
         0.16241262]])

## 내부 조작 함수

### 정렬 함수 : sort

- 다차원 배열도 내부의 원소를 기준으로 처리를 할 때는 순서대로 정렬을 해서 사용할 수 있습니다.

In [248]:
a = np.linspace(1,9,9, dtype=np.int32)

In [249]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [250]:
np.random.shuffle(a)

In [251]:
a

array([8, 6, 1, 9, 5, 2, 4, 3, 7], dtype=int32)

In [232]:
b = np.sort(a)

In [233]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [234]:
a

array([4, 2, 8, 3, 7, 1, 5, 9, 6], dtype=int32)

In [235]:
a.sort()

In [236]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [252]:
b1 = a.reshape(3,3)

In [253]:
b1

array([[8, 6, 1],
       [9, 5, 2],
       [4, 3, 7]], dtype=int32)

In [256]:
np.random.shuffle(b1)

In [257]:
b1

array([[4, 3, 7],
       [9, 5, 2],
       [8, 6, 1]], dtype=int32)

In [260]:
np.sort(b1)

array([[3, 4, 7],
       [2, 5, 9],
       [1, 6, 8]], dtype=int32)

### 정렬함수 : argsort

- 값을 정렬하지 않고 인덱스 정렬은 arg 함수를 사용합니다. 기존 원본 배열의 인덱스를 가지고 배열한 정렬을 반환합니다.

In [261]:
bb = np.linspace(1,6,6, dtype=np.int32)

In [262]:
bb

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [271]:
np.random.shuffle(bb)

In [272]:
bb

array([5, 1, 6, 3, 2, 4], dtype=int32)

In [273]:
c = np.argsort(bb)

In [280]:
c

array([1, 4, 3, 5, 0, 2])

In [281]:
bb

array([5, 1, 6, 3, 2, 4], dtype=int32)

In [275]:
c.dtype  #question np.argsort 하고 data type이 바뀌는 이유?

dtype('int64')

In [279]:
bb[c[0]], bb[c[1]], bb[c[2]], bb[c[3]], bb[c[4]], bb[c[5]]

(1, 2, 3, 4, 5, 6)

### 배열 클래스 변경

- 넘파이 모듈은 다차원 배열인 nmdarray와 행렬을 처리하는 matrix 클래스가 있습니다. 이들은 서로 자료형을 교환할 수 있습니다.

In [282]:
m = np.matrix([1,2,3,4])

In [283]:
m

matrix([[1, 2, 3, 4]])

In [284]:
type(m)

numpy.matrix

__자료형 변경하기__

In [285]:
a = np.asarray(m)

In [286]:
a

array([[1, 2, 3, 4]])

In [287]:
type(a)

numpy.ndarray

In [288]:
m1 = np.asmatrix(a)

In [289]:
m1

matrix([[1, 2, 3, 4]])

In [290]:
type(m1)

numpy.matrix

### 배열의 값 변경

- 다차원 배열을 ones 함수로 만들면 모든 원소의 값이 1 입니다.<br>모든 원소를 다른 값으로 변경하려면 fill 메소드를 사용해서 변경합니다.<br>또한 full 함수는 새로 만드는 배열의 모든 값을 동일하게 처리합니다.

In [291]:
o = np.ones(10)

In [292]:
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [294]:
o.fill(321)

In [295]:
o

array([321., 321., 321., 321., 321., 321., 321., 321., 321., 321.])

In [298]:
a = np.full(o.shape, 99)

In [299]:
a

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [300]:
a = np.full(o.shape, 99.)

In [301]:
a

array([99., 99., 99., 99., 99., 99., 99., 99., 99., 99.])

### 위치변경 및 이동

- 배열의 좌우, 상하의 위치 및 각도에 따라 이동을 시킬 수 있습니다.

In [302]:
array = np.arange(4).reshape((2,2))

In [303]:
array

array([[0, 1],
       [2, 3]])

In [304]:
np.fliplr(array)

array([[1, 0],
       [3, 2]])

In [305]:
np.flipud(array)

array([[2, 3],
       [0, 1]])

In [308]:
np.fliplr(np.flipud(array))

array([[3, 2],
       [1, 0]])

In [309]:
m = np.array([[1,2],[3,4]],int)

In [310]:
m

array([[1, 2],
       [3, 4]])

In [315]:
np.rot90(m), np.rot90(m,2), np.rot90(m,3), np.rot90(m,4)

(array([[2, 4],
        [1, 3]]),
 array([[4, 3],
        [2, 1]]),
 array([[3, 1],
        [4, 2]]),
 array([[1, 2],
        [3, 4]]))

### 배열 내의 원소 점검하기

- 원소의 값에 대한 체크를 할 수 있습니다. 또한 무한대나 nan도 점검할 수 있습니다.

In [316]:
m = np.random.randn(3,5)

In [317]:
m

array([[ 0.89233249, -0.17760658,  1.8349804 , -0.06946602,  0.95761699],
       [-2.02211281,  0.52930752,  0.90502321,  0.17716964,  1.04976568],
       [ 0.65836556,  0.78887321, -0.18504683, -0.76807261,  2.63346282]])

In [318]:
np.isreal(m), np.isinf(m), np.isnan(m)

(array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]),
 array([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]),
 array([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]))

In [341]:
np.isnan(1), np.isnan(np.log(-7))
# http://blog.daum.net/swrush/342

<ipython-input-341-31664152735b>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(1), np.isnan(np.log(-7))


(False, True)

In [342]:
y = [3.7, 6.2, 8.3, -7.6, 5.5]

In [343]:
result = np.sqrt(y)

<ipython-input-343-c5e97f7b7eb6>:1: RuntimeWarning: invalid value encountered in sqrt
  result = np.sqrt(y)


In [344]:
result

array([1.92353841, 2.48997992, 2.88097206,        nan, 2.34520788])

## 배열의 padding 처리


### padding

- 기존 배열 밖에 다른 원소를 더 붙여서 배열을 확장하는 방식입니다.

In [345]:
x = np.arange(1,5).reshape(2,2)

In [346]:
x

array([[1, 2],
       [3, 4]])

In [347]:
z = np.zeros((3,3))

In [348]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [349]:
z[:2, :2] = x

In [350]:
z

array([[1., 2., 0.],
       [3., 4., 0.],
       [0., 0., 0.]])

### padding 함수 1

- 함수 pad를 가지고 배열에 padding을 처리합니다. 상수값으로 padding을 할 때는 constant 문자열을 인자로 전달합니다.

In [355]:
np.pad(x,0,"constant")

array([[1, 2],
       [3, 4]])

In [356]:
np.pad(x,1,"constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [352]:
np.pad(x,(0,1),"constant")

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [353]:
np.pad(x,(1,0),"constant")

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [354]:
np.pad(x,(1,1),"constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [357]:
np.pad(x,(3,3),"constant")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [358]:
x = np.arange(1,5).reshape(2,2)

In [359]:
x

array([[1, 2],
       [3, 4]])

In [360]:
np.pad(x,(0,1),'edge')

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [361]:
np.pad(x,(1,0),"edge")

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [362]:
np.pad(x,(1,1),"edge")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [363]:
np.pad(x,(3,3),'edge')

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4]])

### padding 함수 3

- padding 되는 값을 최대값, 최소값, 평균, 중앙값 등으로 지정할 수 있습니다.

In [364]:
np.pad(x,(3,3), "maximum")

array([[4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4]])

In [365]:
np.pad(x,(1,1), "mean")

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [2, 2, 3, 2]])

In [366]:
np.pad(x,(3,3), "mean")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [367]:
np.pad(x,(3,3), "median")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])