In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## 예제 5-1-5-1  행단위로 처리 

In [3]:
a = np.arange(6).reshape(2,3)

In [4]:
b = np.arange(3)

In [5]:
np.r_

In [6]:
type(np.r_)

numpy.lib.index_tricks.RClass

In [7]:
try :
    np.r_[a,b]
except Exception as e :
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [8]:
c = np.random.randn(2,3)

In [9]:
np.r_[a,c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 2.16460623,  0.83381835, -0.87913713],
       [ 0.38626617,  2.56943661, -0.81360297]])

## 예제 5-1-5-2 열단위로 처리 

In [10]:
np.c_

In [11]:
type(np.c_)

numpy.lib.index_tricks.CClass

In [12]:
np.c_[a,c]

array([[ 0.        ,  1.        ,  2.        ,  2.16460623,  0.83381835,
        -0.87913713],
       [ 3.        ,  4.        ,  5.        ,  0.38626617,  2.56943661,
        -0.81360297]])

## 예제 5-1-5-3 행과 열을 조합해서 처리 

In [13]:
d = np.arange(4)

In [14]:
np.c_[np.r_[a,c],d]

array([[ 0.        ,  1.        ,  2.        ,  0.        ],
       [ 3.        ,  4.        ,  5.        ,  1.        ],
       [ 2.16460623,  0.83381835, -0.87913713,  2.        ],
       [ 0.38626617,  2.56943661, -0.81360297,  3.        ]])