In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

##  예제 5-1-3-1  두 배열을 단순히 결합하기

In [3]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [5]:
b = np.linspace(7,13,6, dtype=np.int32).reshape(2,3)

In [6]:
b

array([[ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [7]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [8]:
np.concatenate([a,b], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [9]:
c = np.linspace(7,15,8, dtype=np.int32).reshape(2,4)

In [10]:
c

array([[ 7,  8,  9, 10],
       [11, 12, 13, 15]], dtype=int32)

In [11]:
try :
    np.concatenate([a,c], axis=0)
except Exception as e :
    print(e)

all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4


In [12]:
np.concatenate([a,b], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]], dtype=int32)

In [13]:
np.concatenate([a,c], axis=1)

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 15]], dtype=int32)

## 예제 5-1-3-2  배열을 쌓기

In [14]:
x = np.array([1,2,3])

In [15]:
y = np.array([4,5,6])

In [16]:
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.stack([x,y],axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
z = np.array([7,8,9,10])

In [19]:
try :
    np.stack([x,z],axis=0)
except Exception as e :
    print(e)

all input arrays must have the same shape


In [20]:
np.stack([x,y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
try :
    np.stack([x,z],axis=1)
except Exception as e :
    print(e)

all input arrays must have the same shape


In [22]:
np.stack([x,y], axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

## 예제 5-1-3-3  축 지정없이 배열을 쌓기

In [23]:
a = np.vstack([x,y])

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.vstack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
np.vstack([[a,a]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [27]:
b = np.hstack([x,y])

In [28]:
b

array([1, 2, 3, 4, 5, 6])

In [29]:
np.hstack([b,b])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [33]:
c = b.reshape(1,6)

In [34]:
np.hstack([c,c])

array([[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]])

In [36]:
np.row_stack([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
np.column_stack([b,b])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

## 예제 5-1-3-4  축을 확대하기

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.dstack([a,a])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [42]:
x = np.array([[1],[2],[3]])

In [46]:
x

array([[1],
       [2],
       [3]])

In [44]:
y = np.array([[2],[3],[4]])

In [47]:
y

array([[2],
       [3],
       [4]])

In [45]:
np.dstack([x,y])

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])