In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.0'

## 예제 5-3-3-1  계산된 값을 이용해서 패딩하기

In [3]:
x = np.arange(1,5).reshape(2,2)

In [4]:
x

array([[1, 2],
       [3, 4]])

In [5]:
np.pad(x,(0,1),"mean")

array([[1, 2, 2],
       [3, 4, 4],
       [2, 3, 2]])

In [6]:
np.pad(x,(1,0),"mean")

array([[2, 2, 3],
       [2, 1, 2],
       [4, 3, 4]])

In [7]:
np.pad(x,(1,1),"mean")

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [2, 2, 3, 2]])

In [8]:
np.pad(x,(3,3),"mean")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [9]:
np.pad(x,(3,3),"median")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])