In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

##  예제 5-2-1-1  배열을 정렬하기 

In [7]:
a = np.linspace(1,6,6, dtype=np.int32)

In [8]:
a

array([1, 2, 3, 4, 5, 6])

In [10]:
np.random.shuffle(a)

In [11]:
a

array([6, 5, 4, 1, 2, 3])

In [14]:
b = np.sort(a)

In [15]:
b

array([1, 2, 3, 4, 5, 6])

In [16]:
a

array([6, 5, 4, 1, 2, 3])

In [17]:
a.sort()

In [18]:
a

array([1, 2, 3, 4, 5, 6])

In [19]:
bb = np.linspace(1,6,6, dtype=np.int32)

In [20]:
bb

array([1, 2, 3, 4, 5, 6])

In [21]:
np.random.shuffle(bb)

In [22]:
bb

array([6, 5, 3, 4, 1, 2])

In [23]:
c = np.argsort(bb)

In [24]:
c

array([4, 5, 2, 3, 1, 0], dtype=int64)

In [25]:
bb[c[0]]

1

In [26]:
bb[c[1]]

2

In [27]:
d = np.random.randn(3,4)

In [28]:
d

array([[ 0.14347153, -0.59365036,  0.28558578,  1.57187591],
       [-0.33491425, -0.18621171, -0.96583627, -0.12798826],
       [-0.20775826, -0.91666505, -0.68249821, -0.79824763]])

In [29]:
np.sort(d, axis=1)

array([[-0.59365036,  0.14347153,  0.28558578,  1.57187591],
       [-0.96583627, -0.33491425, -0.18621171, -0.12798826],
       [-0.91666505, -0.79824763, -0.68249821, -0.20775826]])

In [30]:
np.sort(d, axis=0)

array([[-0.33491425, -0.91666505, -0.96583627, -0.79824763],
       [-0.20775826, -0.59365036, -0.68249821, -0.12798826],
       [ 0.14347153, -0.18621171,  0.28558578,  1.57187591]])

## 예제 5-2-1-2  다양한 배열 정렬하기

In [3]:
v1 = np.array(['문','홍','강'])

In [8]:
np.sort(v1)

array(['강', '문', '홍'], dtype='<U1')

In [9]:
v2 = np.array(['소을','가고','도나'])

In [13]:
np.sort(v2)

array(['가고', '도나', '소을'], dtype='<U2')

In [21]:
res = []
for f,l  in zip(v1,v2) :
    res.append(l + f )
    

In [22]:
res

['소을문', '가고홍', '도나강']

In [23]:
v3 = np.array(res)

In [24]:
v3

array(['소을문', '가고홍', '도나강'], dtype='<U3')

In [25]:
np.sort(v3)

array(['가고홍', '도나강', '소을문'], dtype='<U3')

In [26]:
np.lexsort((v1,v2))

array([1, 2, 0])