In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## 예제 5-3-1-1  배열을 확장해서 패딩 처리하기

In [4]:
x = np.arange(1,5).reshape(2,2)

In [5]:
x

array([[1, 2],
       [3, 4]])

In [6]:
z = np.zeros((3,3))

In [7]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
z[:2, :2] = x

In [9]:
z

array([[1., 2., 0.],
       [3., 4., 0.],
       [0., 0., 0.]])

In [11]:
np.pad(x,0,"constant")

array([[1, 2],
       [3, 4]])

In [9]:
np.pad(x,(0,1),"constant")

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [10]:
np.pad(x,(1,0),"constant")

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [11]:
np.pad(x,(1,1),"constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [10]:
np.pad(x,1,"constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [12]:
np.pad(x,(3,3),"constant")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
np.pad(x,(3,0),"constant")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2],
       [0, 0, 0, 3, 4]])

In [14]:
np.pad(x,(0,3),"constant")

array([[1, 2, 0, 0, 0],
       [3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])