In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 2-3-2-1  하삼각행렬 알아보기

In [3]:
a = np.arange(1,10).reshape(3,3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [6]:
np.tril(a,k=-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

## 예제 2-3-2-2  상삼각행렬 알아보기

In [7]:
b = np.arange(1,10).reshape(3,3)

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [10]:
np.triu(b,k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

## 예제 2-3-2-3  삼각행렬 전치관계 알아보기

In [11]:
c = np.triu(b)

In [12]:
c

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [13]:
c.T

array([[1, 0, 0],
       [2, 5, 0],
       [3, 6, 9]])

In [14]:
d = np.tril(b)

In [15]:
d.T

array([[1, 4, 7],
       [0, 5, 8],
       [0, 0, 9]])

In [16]:
d * d

array([[ 1,  0,  0],
       [16, 25,  0],
       [49, 64, 81]])

In [17]:
c*c

array([[ 1,  4,  9],
       [ 0, 25, 36],
       [ 0,  0, 81]])

In [18]:
d * c

array([[ 1,  0,  0],
       [ 0, 25,  0],
       [ 0,  0, 81]])