In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 2-2-4-1  배열 확장 및 축소하기 

In [3]:
x = np.array([1,2])

In [4]:
x

array([1, 2])

In [5]:
y = np.expand_dims(x, axis=1)

In [6]:
y

array([[1],
       [2]])

In [7]:
z = np.expand_dims(x, axis=0)

In [8]:
z

array([[1, 2]])

## 예제 2-2-4-2  1차원 배열로 데이터를 보기

In [9]:
x = np.array([[1,4,5],[4,5,6],[7,8,9]])

In [10]:
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [12]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [13]:
np.may_share_memory(x.flatten(),x)

False

In [14]:
np.may_share_memory(x.ravel(),x)

True