In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 2-3-7-1  전치행렬 알아보기

In [3]:
a = np.array([[1,2],[3,4]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
a.T

array([[1, 3],
       [2, 4]])

In [6]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [7]:
np.transpose(a)

array([[1, 3],
       [2, 4]])