In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

## 예제 2-4-2-1 행중심 처리

In [4]:
x = np.array([[1,3],[4,5]], order='C')

In [5]:
x

array([[1, 3],
       [4, 5]])

In [6]:
x.tobytes()

b'\x01\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00'

In [7]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## 예제 2-4-2-2 열중심 처리

In [8]:
y = np.array([[1,3],[4,5]], order='F')

In [9]:
y

array([[1, 3],
       [4, 5]])

In [10]:
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [12]:
y.ravel('F')

array([1, 4, 3, 5])

In [13]:
y.ravel()

array([1, 3, 4, 5])