In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 2-3-1-1  행렬의 궤적 알아보기

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [5]:
a.shape

(3, 3)

In [6]:
np.trace(a)

14

In [7]:
a.trace()

14

## 예제 2-3-1-2  대각행렬을 알아보기

In [8]:
b = np.array([[1,0,0],[0,3,0],[0,0,5]])

In [9]:
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [10]:
b.diagonal()

array([1, 3, 5])

In [11]:
np.diagonal(b)

array([1, 3, 5])

## 예제 2-3-1-3  대각행렬을 만들기

In [12]:
c = np.diag(np.arange(1,4))

In [13]:
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
d = np.diag(np.arange(1,4),k=1)

In [15]:
d

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [16]:
e = np.diag(np.arange(1,4),k=-1)

In [17]:
e

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [18]:
f = np.diag([[1,2],[3,4]])

In [19]:
f

array([1, 4])

In [20]:
g = np.diagonal([[1,2],[3,4]])

In [21]:
g

array([1, 4])

## 예제 2-3-1-4  단위행렬을 만들기

In [22]:
h = np.eye(3,3)

In [23]:
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
i = np.eye(3,3,k=1)

In [25]:
i

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [26]:
j = np.eye(3,3,k=-1)

In [27]:
j

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [28]:
k = np.diag([4,4,4])

In [29]:
k

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [30]:
k * 1/4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 예제 2-3-1-5  항등행렬을 만들기

In [31]:
l = np.identity(3)

In [32]:
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
s = np.arange(1,10).reshape(3,3)

In [34]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
s.dot(l)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])