In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 2-3-5-1  행바꿈 알아보기

In [3]:
a = np.arange(1,10).reshape(3,3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b = np.eye(3, dtype='int')

In [6]:
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
np.dot(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c = np.array([[0,1,0],[1,0,0],[0,0,1]])

In [9]:
np.dot(a,c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])