In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 10-1-2-1  연립 방적식 풀기

### 방정식 
     
    3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

In [3]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])

In [4]:
x = np.linalg.solve(a, b)

In [5]:
x

array([2., 3.])

In [6]:
np.allclose(np.dot(a, x), b)

True

In [7]:
A = np.array( [[1,0,0],[1,1,1],[6,7,0]])

In [8]:
b =np.array([0,24,0])

In [9]:
A_1 = np.linalg.inv(A)

In [10]:
A_1

array([[ 1.        ,  0.        ,  0.        ],
       [-0.85714286, -0.        ,  0.14285714],
       [-0.14285714,  1.        , -0.14285714]])

In [11]:
x = np.dot(A_1, b) 

In [12]:
x

array([ 0.,  0., 24.])

In [13]:
np.allclose(np.dot(A_1, b), x)

True

In [14]:
np.linalg.solve(A, b)

array([ 0., -0., 24.])

In [15]:
np.allclose(np.dot(A_1, b), x)

True

## 예제 10-1-2-2   lstsq 함수로 연립 방적식 풀기

###  lstsq

lstsq 명령은 행렬  𝐴
 와  𝑏  모두 인수로 받고 뒤에서 설명할 최소자승문제(least square problem)의 답 x, 잔차제곱합(residual sum of squares) resid, 랭크(rank) rank, 특잇값(singular value) s를 반환한다. 미지수와 방정식의 개수가 같고 행렬  𝐴의 역행렬이 존재하면 최소자승문제의 답과 선형 연립방정식의 답이 같으므로 lstsq 명령으로 선형 연립방정식을 풀 수도 있다. 최소자승문제, 랭크, 특잇값에 대해서는 뒤에서 자세히 설명할 것이다.


lstsq 명령을 사용하는 것이 inv 명령을 사용하는 것보다 수치오차가 적고 코드도 간단하므로 선형 연립방정식의 해를 구할 때도 lstsq 명령을 사용하는 것을 권장한다.

In [16]:
np.linalg.matrix_rank(A)

3

In [17]:
x, resid, rank, singulr = np.linalg.lstsq(A,b, rcond=-1)

In [18]:
x

array([ 5.36506792e-15, -3.77475828e-15,  2.40000000e+01])

In [19]:
np.allclose(np.dot(A, x), b)

True

### resid는 잔차벡터의  𝑒=𝐴𝑥−𝑏 의 제곱합, 즉 놈의 제곱이다

In [20]:
np.linalg.norm(A @ x - b)

1.3252900089356776e-14

In [21]:
np.allclose(np.linalg.norm(A @ x - b) , 0)

True

In [22]:
resid

array([], dtype=float64)

### 특이값분해(singular value decomposition;svd)에 

https://blog.naver.com/cjh226/220861349129

https://darkpgmr.tistory.com/106

In [23]:
u, s_, vh = np.linalg.svd(A, full_matrices=True)

In [24]:
s_

array([9.3509151 , 1.        , 0.74858984])

In [25]:
singulr

array([9.3509151 , 1.        , 0.74858984])