In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 10-3-1-1  convolve 함수 처리

In [3]:
a = np.array([0, 1, 2, 3, 4, 5,6])

In [4]:
v = np.array([0.2, 0.7])

In [5]:
same = np.convolve(a,v, mode='same')

In [6]:
same.shape

(7,)

In [7]:
same

array([0. , 0.2, 1.1, 2. , 2.9, 3.8, 4.7])

In [8]:
a_ = np.array([0,0, 1, 2, 3, 4, 5,6])

In [9]:
v_ = np.roll(v,1)

In [10]:
v_

array([0.7, 0.2])

In [11]:
np.dot([0,0], v_)

0.0

In [12]:
np.dot([0,1], v_)

0.2

In [13]:
ll = []

In [14]:
for i in range(7) :
    ll.append(np.dot(a_[i : i+2], v_).tolist())

In [15]:
ll

[0.0, 0.2, 1.1, 2.0, 2.8999999999999995, 3.8, 4.7]

In [16]:
np.allclose(same, ll)

True

In [17]:
full = np.convolve(a,v, mode='full')

In [18]:
full.shape

(8,)

In [19]:
full

array([0. , 0.2, 1.1, 2. , 2.9, 3.8, 4.7, 4.2])

In [20]:
ll = []

In [21]:
a__ = np.array([0,0, 1, 2, 3, 4, 5,6,0])

In [22]:
for i in range(8) :
    ll.append(np.dot(a__[i : i+2], v_).tolist())

In [23]:
ll

[0.0, 0.2, 1.1, 2.0, 2.8999999999999995, 3.8, 4.7, 4.199999999999999]

In [24]:
valid = np.convolve(a,v, mode='valid')

In [25]:
valid.shape

(6,)

In [26]:
valid

array([0.2, 1.1, 2. , 2.9, 3.8, 4.7])

In [27]:
ll = []

In [28]:
a___ = np.array([0, 1, 2, 3, 4, 5,6])

In [29]:
for i in range(6) :
    ll.append(np.dot(a___[i : i+2], v_).tolist())

In [30]:
ll

[0.2, 1.1, 2.0, 2.8999999999999995, 3.8, 4.7]

In [31]:
w = np.array([1,3,3,0])

In [32]:
x = np.array([2,4,6,8,0,8,0])

In [33]:
w_r = np.flip(w)

In [34]:
w_r

array([0, 3, 3, 1])

In [35]:
np.correlate(x, w_r,mode='same')

array([10, 24, 38, 42, 32, 24, 24])

In [36]:
np.convolve(x,w, mode='same')

array([10, 24, 38, 42, 32, 24, 24])

In [37]:
np.correlate(x, w,mode='same')

array([ 6, 18, 32, 46, 30, 32, 24])

In [38]:
np.convolve(x,w_r, mode='same')

array([ 6, 18, 32, 46, 30, 32, 24])