In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

## 예제 7-6-1-1 배열의 유일한 원소 확인하기

In [3]:
x = np.array([[1,2,3],[4,5,6],[3,4,5]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [7]:
type(np.unique)

function

In [6]:
np.unique(x)

array([1, 2, 3, 4, 5, 6])

## 예제 7-6-1-2  포함여부 확인하기

In [8]:
x = np.arange(5)

In [9]:
x

array([0, 1, 2, 3, 4])

In [10]:
type(np.in1d)

function

In [14]:
np.in1d(5,x)

array([False])

In [16]:
np.in1d(4,x)

array([ True])

In [18]:
np.in1d([3,4,5],x)

array([ True,  True, False])