In [2]:
import numpy as np

In [3]:
np.__version__

'1.17.2'

## 예제 7-2-2-1  산술연산 처리하기

In [4]:
x = np.array([2,4,5,8,9])

In [5]:
x + x

array([ 4,  8, 10, 16, 18])

In [6]:
np.add(x, x)

array([ 4,  8, 10, 16, 18])

In [7]:
x / x

array([1., 1., 1., 1., 1.])

In [8]:
np.true_divide(x,x)

array([1., 1., 1., 1., 1.])

In [9]:
x // x

array([1, 1, 1, 1, 1], dtype=int32)

In [10]:
np.floor_divide(x,x)

array([1, 1, 1, 1, 1], dtype=int32)

In [12]:
x // 1.5

array([1., 2., 3., 5., 6.])

In [10]:
np.mod(4,3)

1

In [11]:
np.remainder(4,3)

1

In [12]:
np.divmod(4,3)

(1, 1)

In [13]:
 np.modf([0, 3.5])

(array([0. , 0.5]), array([0., 3.]))

In [14]:
d = np.reciprocal(2.)

In [15]:
d

0.5

In [16]:
d * 2

1.0