In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

## 예제 7-2-4-1  상수 알아보기

In [3]:
np.e

2.718281828459045

In [4]:
np.pi

3.141592653589793

In [9]:
type(np.e), type(np.pi)

(float, float)

In [5]:
x = np.arange(5)

In [6]:
np.e * x

array([ 0.        ,  2.71828183,  5.43656366,  8.15484549, 10.87312731])

In [7]:
np.round(np.pi * x,2)

array([ 0.  ,  3.14,  6.28,  9.42, 12.57])

In [10]:
np.inf == np.Inf

True

In [11]:
np.inf == np.Infinity

True

In [12]:
type(np.inf)

float

In [12]:
np.sign(np.inf)

1.0

In [15]:
np.negative(np.inf)

-inf

In [16]:
np.negative(np.nan)

nan

In [13]:
np.nan == np.NaN

False

In [14]:
type(np.nan)

float

In [15]:
type(np.NaN)

float

In [16]:
np.nan * 5

nan

## 예제 7-2-4-2  무한대, 결측값 원소 확인

In [19]:
a = np.array([10,np.inf,np.nan])

In [20]:
a

array([10., inf, nan])

In [21]:
np.isinf(a)

array([False,  True, False])

In [24]:
np.isfinite(a)

array([ True, False, False])

In [22]:
np.isnan(a)

array([False, False,  True])

In [28]:
np.isnat(np.datetime64("NaT"))

True

In [29]:
x = np.array([8, np.inf, -np.inf])

In [33]:
np.isinf(x)

array([False,  True,  True])

In [31]:
np.isposinf(x)

array([False,  True, False])

In [32]:
np.isneginf(x)

array([False, False,  True])

In [35]:
np.nan_to_num(x)

array([ 8.00000000e+000,  1.79769313e+308, -1.79769313e+308])

In [36]:
np.nan_to_num(a)

array([1.00000000e+001, 1.79769313e+308, 0.00000000e+000])

## 예제 7-2-4-3  결측값이 들어있는 값 계산 

In [38]:
a = np.array([[1, np.nan], [3, 4]])

In [42]:
np.mean(a, axis=0)

array([ 2., nan])

In [40]:
np.nanmean(a, axis=0)

array([2., 4.])

In [43]:
np.mean(a, axis=1)

array([nan, 3.5])

In [41]:
np.nanmean(a, axis=1)

array([1. , 3.5])