In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-3-1-1  배열로 원소를 검색하기

In [3]:
x = np.arange(1,15)

In [4]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
pos = np.array([10])

In [6]:
pos

array([10])

In [7]:
x[10]

11

In [8]:
x[pos]

array([11])

In [9]:
pos2 = np.array([1,2,2,2])

In [10]:
x[pos2]

array([2, 3, 3, 3])

In [11]:
c = x[pos2]

In [12]:
np.may_share_memory(x,c)

False

In [13]:
y = x[:4]

In [14]:
np.may_share_memory(x,y)

True

In [15]:
len(x)

14

In [16]:
try :
    x[[15]]
    
except Exception as e :
    print(e)

index 15 is out of bounds for axis 0 with size 14


In [17]:
d = x[[-5,-4,-3,-2,-1]]

In [18]:
d

array([10, 11, 12, 13, 14])

In [19]:
d[0] = 100

In [20]:
x[-5]

10

## 예제 3-3-1-2  이차원 배열의 원소를 검색하기

In [21]:
x = np.arange(16).reshape(4,4)

In [22]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [24]:
x[[-1,-2]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [25]:
x[[1,2],[2,3]]

array([ 6, 11])

## 예제 3-3-1-3  ix_ 를 이용해서 검색하기

In [26]:
a = np.array([[2,3,4,5],[8,9,0,1]])

In [27]:
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [28]:
a[[0,1],[0,1]]

array([2, 9])

In [29]:
a[tuple([[0,1],[0,1]])]

array([2, 9])

In [30]:
type(np.ix_)

function

In [31]:
a[np.ix_([0,1],[0,1])]

array([[2, 3],
       [8, 9]])