In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-2-3  논리연산 사용상 주의

In [3]:
L = np.arange(0,12)

In [4]:
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
try :
    L and L
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [6]:
np.logical_and(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [7]:
L[np.logical_and(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.logical_or(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [9]:
L[np.logical_or(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.logical_not(L)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False])

In [11]:
L[np.logical_not(L)]

array([0])

In [12]:
LL = np.arange(0,12).astype(np.bool)

In [13]:
LL

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [14]:
LL & LL

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [15]:
LL | LL 

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [16]:
~ LL

array([ True, False, False, False, False, False, False, False, False,
       False, False, False])