In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-3-4-1 차원의 축소

In [3]:
x = np.arange(9).reshape(3,3)

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
a = x[1: , 1:]

In [6]:
a

array([[4, 5],
       [7, 8]])

In [7]:
np.may_share_memory(x,a)

True

In [8]:
b = x[1: , [1,2]]

In [9]:
b

array([[4, 5],
       [7, 8]])

In [10]:
np.may_share_memory(x,b)

False

## 예제 3-3-4-2 확대 검색 하기

In [11]:
a = np.reshape(np.arange(10), (2,5))

In [12]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b = a[[1,1,1]]

In [14]:
b.shape

(3, 5)

In [15]:
b

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [16]:
c = a[[1,1,1], np.newaxis]

In [17]:
c.shape

(3, 1, 5)

In [18]:
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [19]:
d = a[np.newaxis, [1,1,1]]

In [20]:
d.shape

(1, 3, 5)

In [21]:
d

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [22]:
tuple([[1,1],[0,1]])

([1, 1], [0, 1])

In [23]:
a[tuple([[1,1],[0,1]])]

array([5, 6])

In [24]:
tuple([[[1,1],[0,1]]])

([[1, 1], [0, 1]],)

In [25]:
a[tuple([[[1,1],[0,1]]])]

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [26]:
e = a[[[1,1],[0,1]], :]

In [27]:
e.shape

(2, 2, 5)

In [28]:
e

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [29]:
f = a[[[1,1],[0,1]], :1]

In [30]:
f.shape

(2, 2, 1)

In [31]:
f

array([[[5],
        [5]],

       [[0],
        [5]]])

In [32]:
g = a[[[1,1],[0,1]], [0]]

In [33]:
g.shape

(2, 2)

In [34]:
g

array([[5, 5],
       [0, 5]])