In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 8-3-2-1 로그함수 법칙 알아보기

In [3]:
x = np.arange(10000,1000000,100000)

In [4]:
x

array([ 10000, 110000, 210000, 310000, 410000, 510000, 610000, 710000,
       810000, 910000])

In [5]:
type(np.log)

numpy.ufunc

In [6]:
np.log(1)

0.0

In [7]:
np.log(np.e)

1.0

In [8]:
np.log(100)

4.605170185988092

In [9]:
np.log(10) + np.log(10)

4.605170185988092

In [10]:
np.log(2/5)

-0.916290731874155

In [11]:
np.log(2) - np.log(5)

-0.916290731874155

In [12]:
np.log(np.power(100,2))

9.210340371976184

In [13]:
2 * np.log(100)

9.210340371976184

In [14]:
np.log(100)

4.605170185988092

In [15]:
np.log10(100) / np.log10(np.e)

4.605170185988092

In [16]:
np.log(100)

4.605170185988092

In [17]:
1/ np.log(100)

0.21714724095162588

In [18]:
np.log(100) *  (1/np.log(100))

0.9999999999999999

In [19]:
np.allclose(np.log(100) *  (1/np.log(100)),1)

True

## 예제 8-3-2-2 로그함수 알아보기

In [20]:
np.log(x)

array([ 9.21034037, 11.60823564, 12.25486281, 12.64432758, 12.92391244,
       13.142166  , 13.32121424, 13.47302025, 13.60478953, 13.72119988])

In [21]:
np.ceil(np.log(x))

array([10., 12., 13., 13., 13., 14., 14., 14., 14., 14.])

In [22]:
np.exp(9.21034037)

9999.99998023818

In [23]:
np.allclose(np.exp(9.21034037), 10000)

True

In [24]:
np.log10(x)

array([4.        , 5.04139269, 5.32221929, 5.49136169, 5.61278386,
       5.70757018, 5.78532984, 5.85125835, 5.90848502, 5.95904139])

In [25]:
np.ceil(np.log10(x))

array([4., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [26]:
np.power(10,4)

10000

In [27]:
np.log10(110000)

5.041392685158225

In [28]:
np.power(10, 5.041392685158225)

110000.00000000009

In [29]:
np.log2(32)

5.0

In [30]:
np.power(2,5)

32

In [31]:
np.log1p(20)

3.044522437723423

In [32]:
np.log(1+20)

3.044522437723423