In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 8-2-1-1 논리연산 이해하기

In [3]:
x = np.arange(2.0,4)

In [4]:
x

array([2., 3.])

In [5]:
1 &  2 

0

In [6]:
np.bitwise_and(1,2)

0

In [7]:
True & False

False

In [8]:
True and False

False

In [9]:
np.logical_and(True,False)

False

In [10]:
try :
    x and x
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [11]:
np.logical_and(x,x)

array([ True,  True])

In [12]:
np.logical_or(x,x)

array([ True,  True])

In [13]:
try :
    x or x
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [14]:
y = x < 5

In [15]:
y

array([ True,  True])

In [16]:
z = x > 5

In [17]:
z

array([False, False])

In [18]:
z | y

array([ True,  True])

In [19]:
try :
    z and y
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [20]:
z ^ y

array([ True,  True])

In [21]:
np.logical_xor(z,y)

array([ True,  True])

In [22]:
try :
    not z
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [23]:
~ z

array([ True,  True])

In [24]:
np.logical_not(z)

array([ True,  True])

In [25]:
try :
    not z
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
