In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

## 예제 8-1-5-1  비트 연산 알아보기

In [3]:
np.binary_repr(12)

'1100'

In [4]:
a = np.array([1,2,3])

In [5]:
np.binary_repr(a[0])

'1'

In [6]:
try :
    np.binary_repr(2.3)
except Exception as e :
    print(e)

'float' object cannot be interpreted as an integer


In [7]:
np.bitwise_and(a,a)

array([1, 2, 3], dtype=int32)

In [8]:
np.bitwise_or(a,a)

array([1, 2, 3], dtype=int32)

In [13]:
np.bitwise_xor(a,a)

array([0, 0, 0], dtype=int32)

In [14]:
np.bitwise_not(a)

array([-2, -3, -4], dtype=int32)

In [16]:
np.binary_repr(10)

'1010'

In [15]:
np.invert(10)

-11

In [17]:
np.bitwise_not(10)

-11

In [18]:
np.binary_repr(-11)

'-1011'

In [19]:
10 *2

20

In [20]:
np.binary_repr(20)

'10100'

In [22]:
np.left_shift(10,1)

20

In [23]:
10 // 2

5

In [24]:
np.binary_repr(5)

'101'

In [25]:
np.right_shift(10,1)

5