In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 8-1-3-1  부호 및 절대값 처리

In [3]:
x = np.array([2,4,-5,8,-9])

In [4]:
x

array([ 2,  4, -5,  8, -9])

In [5]:
np.sign(x)

array([ 1,  1, -1,  1, -1])

In [6]:
np.negative(x)

array([-2, -4,  5, -8,  9])

In [7]:
np.positive(x)

array([ 2,  4, -5,  8, -9])

In [8]:
np.abs(x)

array([2, 4, 5, 8, 9])

In [9]:
np.absolute(x)

array([2, 4, 5, 8, 9])

In [10]:
np.sign(np.inf)

1.0

In [11]:
np.negative(np.inf)

-inf

In [12]:
np.negative(np.nan)

nan

## 예제 8-1-3-2  제곱, 제곱근 처리 

In [13]:
a = np.arange(10)

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [16]:
np.power(a,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [17]:
np.power(a,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [18]:
np.sqrt(np.power(a,2))

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])