In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 8-2-3-1  연속되는 수의 합을 계산하기

In [3]:
a = np.arange(1,11)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sum(a)

55

In [6]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [7]:
b = np.arange(1,11).reshape(2,5)

In [8]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.sum(b, axis=0)

array([ 7,  9, 11, 13, 15])

In [10]:
np.sum(b, axis=1)

array([15, 40])

In [11]:
np.cumsum(b, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15]], dtype=int32)

In [12]:
np.cumsum(b, axis=1)

array([[ 1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40]], dtype=int32)

## 예제 8-2-3-2 연속되는 수의 곱을 계산하기

In [13]:
np.prod(b)

3628800

In [14]:
np.prod(b, axis=0)

array([ 6, 14, 24, 36, 50])

In [15]:
np.prod(b, axis=1)

array([  120, 30240])

In [16]:
np.cumprod(b)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [17]:
np.cumprod(b ,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6, 14, 24, 36, 50]], dtype=int32)

In [18]:
np.cumprod(b ,axis=1)

array([[    1,     2,     6,    24,   120],
       [    6,    42,   336,  3024, 30240]], dtype=int32)

## 예제 8-2-3-3  결측값을 제외하고 합과 곱을 계산하기

In [19]:
c = np.arange(1,11).reshape(2,5).astype('float')

In [20]:
c[0,2] = np.nan

In [21]:
c[1,2] = np.nan

In [22]:
c

array([[ 1.,  2., nan,  4.,  5.],
       [ 6.,  7., nan,  9., 10.]])

In [23]:
np.sum(c)

nan

In [24]:
np.nansum(c)

44.0

In [25]:
np.nancumsum(c)

array([ 1.,  3.,  3.,  7., 12., 18., 25., 25., 34., 44.])

In [26]:
np.prod(c)

nan

In [27]:
np.nanprod(c)

151200.0

In [28]:
np.nancumprod(c)

array([1.000e+00, 2.000e+00, 2.000e+00, 8.000e+00, 4.000e+01, 2.400e+02,
       1.680e+03, 1.680e+03, 1.512e+04, 1.512e+05])