In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 8-5-1  삼각함수 알아보기

In [3]:
a = np.array((0., 30., 45., 60., 90.))

In [4]:
a

array([ 0., 30., 45., 60., 90.])

In [5]:
np.sin(a* np.pi / 180.)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.sin(np.radians(a))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
np.cos(a* np.pi / 180.)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [8]:
np.cos(np.radians(a))

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [9]:
np.tan(a* np.pi / 180.)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [10]:
np.tan(np.radians(a))

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])