In [5]:
import numpy as np
np.__version__

'1.19.2'

# Chapter 12. 선형대수 알아보기  
> 수학의 소인수분해처럼 선형대수의 행렬도 여러 분해가 가능합니다. 하나의 행렬을 분해하는 여러가지 함수들을 알아봅시다.
[넘파이 선형대수 참고](https://rfriend.tistory.com/380)

## 01. LU, QR 분해 
### 01-1. LU 분해  
LU 분해는 정사각형행렬 A를 하삼각행렬(Lower triangular matrix)과 상삼각행렬(Upper triangular matrix)의 곱으로 표현하는 분해입니다. 여기서 치환행렬(Permutation matrix)도 함께 곱으로 나타내기도 합니다.즉, A=LU


In [6]:
import scipy as sp
from scipy import linalg as LA

In [7]:
A = np.array([[7,3,-1,2], [3,8,1,-4], [-1,1,4,-1], [2,-4,-1,6]])
A

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])

In [11]:
P, L, U = LA.lu(A)  # LU 분해를 lu 함수로 실행
P

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])

In [10]:
U

array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])

### 역행렬이 존재하는 조건 : det(A) ≠ 0   
[행렬식 계산 참고](http://blog.naver.com/PostView.nhn?blogId=mykepzzang&logNo=221080004072)  
<img src="https://t1.daumcdn.net/cfile/tistory/255D184E565C6C403D" align='left'>

In [15]:
a = LA.det(L)
a

1.0

In [18]:
b = LA.det(U)
b

315.0000000000001

In [19]:
np.dot(a, b)

315.0000000000001

In [20]:
LA.det(A)

315.0000000000001

In [17]:
np.dot(L, U)

array([[ 7.,  3., -1.,  2.],
       [ 3.,  8.,  1., -4.],
       [-1.,  1.,  4., -1.],
       [ 2., -4., -1.,  6.]])

### 01-2. LU 분해와 연립방정식 풀기

In [21]:
A = np.array([[2,5,8,7], [5,2,2,8], [7,5,6,6], [5,4,4,8]])
lu, piv = LA.lu_factor(A)
lu

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.28571429,  3.57142857,  6.28571429,  5.28571429],
       [ 0.71428571,  0.12      , -1.04      ,  3.08      ],
       [ 0.71428571, -0.44      , -0.46153846,  7.46153846]])

In [22]:
piv

array([2, 2, 3, 3], dtype=int32)

In [23]:
P, L, U = LA.lu(A)
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.28571429,  1.        ,  0.        ,  0.        ],
       [ 0.71428571,  0.12      ,  1.        ,  0.        ],
       [ 0.71428571, -0.44      , -0.46153846,  1.        ]])

In [24]:
U

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
       [ 0.        ,  0.        , -1.04      ,  3.08      ],
       [ 0.        ,  0.        ,  0.        ,  7.46153846]])

In [27]:
A = np.array([[2,5,8,7], [5,2,2,8], [7,5,6,6], [5,4,4,8]])
b = np.array([1,1,1,1])
lu, piv = LA.lu_factor(A)
x = LA.lu_solve((lu, piv), b)
x

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [28]:
np.allclose(A @ x - b, np.zeros((4,)))

True

In [29]:
x_ = np.linalg.solve(A, b)
x_

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [30]:
np.dot(np.linalg.inv(A), b)

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [31]:
np.dot(A, x_)

array([1., 1., 1., 1.])

In [32]:
A @ x

array([1., 1., 1., 1.])

### 01-2. QR 분해  
QR 분해(QR decomposition or QR factorization)는 임의의 행렬을 직교행렬과 상삼각행렬의 곱으로 분해합니다. 즉, 행렬 A를 QR로 인수분해합니다. 여기서 Q는 직교 좌표이고 R은 상삼각행렬 입니다. 

In [33]:
A = np.array([[12,-51,4], [6,167,-68], [-4,24,-41]])
A

array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])

In [34]:
Q, R = LA.qr(A)
R

array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])

In [35]:
Q

array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])

In [36]:
i = np.dot(Q, Q.T)
i

array([[ 1.00000000e+00,  9.70056801e-17, -2.53402741e-17],
       [ 9.70056801e-17,  1.00000000e+00, -2.88873234e-17],
       [-2.53402741e-17, -2.88873234e-17,  1.00000000e+00]])

In [37]:
I = np.eye(A.shape[0])
np.allclose(i, I)

True

In [41]:
sq = np.fabs(LA.det(Q))
# sq = np.fabs(LA.linalg.det(Q)) 교재 본문에 오류가 있음.
sq

0.9999999999999999

In [42]:
np.allclose(sq, 1)

True

In [43]:
qt = LA.inv(Q)
np.allclose(Q.T, qt)

True

## 02. 고유값, 특이값 분해  
행렬을 하나의 벡터로 분리 또는 여러개의 행렬로 분해하는 고유값 분해와 3개의 행렬로 분해하는 특이값 분해가 있습니다.   
고유값은 주로 정사각형 행렬에 대한 분에에 사용되며, 차원의 다른 행렬일 때는 특이값 분해를 사용합니다.   
### 02-1. 고유값과 고유벡터  
고유값 분해(eigen decomposition)는 고유값(eigen value)과 고유벡터(eigen vector)로 유도되는 고유값 행렬과 고유벡터 행렬에 의해 분해 될 수 있는 행렬의 표현입니다.  
고유값과 고유벡터는 정사각행렬일 때문 분해가 가능합니다. 

In [68]:
A = np.array([[3,0], [8,-1]])
x = np.array([1,2])

고유값을 구하는 산식은 단위행렬에 특정 상수를 곱하고 이를 행렬에 뺀 후에 행렬식을 구하면 0이 나오면 이 상수 값이 고유값이 됩니다. 
<img src="https://i.ibb.co/MMz1b5g/2020-12-01-11-54-21.png" align='left'>

In [49]:
E = np.eye(2) # 단위행렬을 eye함수로 하나 만듭니다.
E

array([[1., 0.],
       [0., 1.]])

<img src="https://i.ibb.co/8MN5VK1/IMG-1291.jpg" align='left'>

In [50]:
LA.det(A - 3*E) # 단위행렬에 3을 곱한 후에 행렬 A에 빽 det 함수로 행렬식을 구하면 0이 나와서 이 상수가 고유값입니다.

0.0

In [72]:
LA.det(A - -1*E)

0.0

고유값과 고유벡터를 구하는 수학적 산식은 아래와 같습니다. 하나의 행렬과 벡터를 행렬곱으로 계산한 것이 상수에 벡터를 곱한 결과와 동일합니다.  
<img src="https://i.ibb.co/gtJVtjH/2020-12-01-12-05-27.png" align="left">

In [51]:
c = np.dot(A, x)
c

array([3, 6])

In [52]:
3*x

array([3, 6])

### 넘파이 모듈을 사용해서 행렬의 고유값과 고유벡터를 구해보자.   
LA.eig 함수에 인자로 전달해서 실행하면 끝! 반환되는 결과가 고유값과 고유벡터  
단, 고유값의 결과가 1차원 배열로 나오는 것은 이 행렬의 고유값이 2개가 있다는 뜻이고 단위벡터도 2차원 배열로 나온것은 두 개의 단위벡터가 있다는 뜻

In [66]:
B = np.array([[1,3], [3,1]])
v, w = LA.eig(B)
v

array([ 4.+0.j, -2.+0.j])

In [57]:
w

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

 첫번째 예제 처럼 산식으로 검증해보자.

In [69]:
E = np.eye(2, 2)
E

array([[1., 0.],
       [0., 1.]])

In [71]:
LA.det(B - (4*E))

0.0

In [73]:
LA.det(B - (-2*E))

0.0

### 3개의 행렬로 분해한 처리  
하나의 정사각행렬을 분해하면 고유벡터의 행렬과 고유값을 단위벡터에 행렬곱한 행렬 고유벡터의 행렬의 전치행렬을 가지고 행렬곱을 한 결과가 분해하기 전에 행렬이다.   
<img src="https://i.ibb.co/Nxqgzzg/2020-12-01-1-44-18.png" align='left'>

In [74]:
C = np.array([[4,3], [3,5]])
C

array([[4, 3],
       [3, 5]])

In [75]:
e, ev = LA.eig(C) # 고유값과 고유벡터를 eig 함수로 계산
e

array([1.45861873+0.j, 7.54138127+0.j])

In [76]:
ev

array([[-0.76301998, -0.6463749 ],
       [ 0.6463749 , -0.76301998]])

In [77]:
# 앞의 예에서 만들어진 단위벡터를 사용해서 고유값과 곱셈해서 2차원 행렬로 변환
e_ = e * E
e_

array([[1.45861873+0.j, 0.        +0.j],
       [0.        +0.j, 7.54138127+0.j]])

In [80]:
# 3개의 행렬을 가지고 행렬곱을 해서 계산하면 원 행렬이 나옴. 
C_ = np.dot(np.dot(ev, e_), ev.T)
C_

array([[4.+0.j, 3.+0.j],
       [3.+0.j, 5.+0.j]])

In [82]:
np.allclose(C_, C) # allclose 함수로 동일한지 확인

True

## 2.2 SVD 분해  
특이값 분해(Singular Value Decomposition, SVD)는 고유값 분해처럼 행렬을 대각화 해서 분해하는 방식입니다.   
고유값 분해는 정사각행렬일 때만 분해가 가능하지만, 특이값 분해는 정사각행렬이 아닐 경우에도 분해가 가능합니다.   
또한 이 행렬이 분해 할 때 구해진 특이값의 개수가 행렬의 랭크를 의미하기도 합니다.  
<img src="https://i.ibb.co/tcz4x4s/2020-12-01-1-59-30.png" align='left'>

In [83]:
A = np.array([[1,0], [1,2]])
U, S, V = np.linalg.svd(A, full_matrices=True) # 분해하는 3개의 행렬을 모두 반환
U

array([[-0.22975292, -0.97324899],
       [-0.97324899,  0.22975292]])

In [84]:
S

array([2.28824561, 0.87403205])

In [85]:
V

array([[-0.52573111, -0.85065081],
       [-0.85065081,  0.52573111]])

보통 3개의 행렬을 확인하면 두개의 특이값 벡터와 하나의 특이값인 것을 알수 있습니다.  
<img src="https://i.ibb.co/n3RhfCC/2020-12-01-1-55-48.png" align='left'>

### 다시 분해된 것을 행렬곱으로 계산해서 원 행렬이 나오는지 알아보자.

In [88]:
# 특이값이 하나의 벡터이므로 이 특이값을 대각행렬로 변형, 대각행렬 하나 만들어 특이값 벡터와 곱을 통해 변환하자.
E = np.eye(2)
SE = S * E 

# 위에서 만들어진 직교행렬과 행렬곱을 구하자.
np.dot(U, np.dot(SE, V))

array([[ 1.00000000e+00, -6.10622664e-16],
       [ 1.00000000e+00,  2.00000000e+00]])

In [89]:
# np.allclose 함수로 동일한지 확인
np.allclose(A, np.dot(U, np.dot(SE, V)))

True

In [91]:
# 3행 2열의 배열을 만들고 이 행렬을 특이값 분해
B = np.array([[1,0], [1,2], [3,3]])
U_, S_, V_ = np.linalg.svd(B, full_matrices=True)
U_

array([[-0.1404708 ,  0.75576256, -0.63960215],
       [-0.44811108, -0.6245843 , -0.63960215],
       [-0.88287282,  0.19676738,  0.42640143]])

In [92]:
S_

array([4.80055841, 0.97705628])

In [93]:
V_

array([[-0.67433829, -0.73842256],
       [ 0.73842256, -0.67433829]])

In [94]:
# 특이값을 대각행렬로 바꾸려고 할 때 정사각행렬이 아니므로 대각 행렬도 3행 2열에 맞춘 대각선을 반영
E3 = np.eye(3)[:, :2]
SE3 = S_ * E3
SE3

array([[4.80055841, 0.        ],
       [0.        , 0.97705628],
       [0.        , 0.        ]])

In [95]:
# 행렬 곱을 통해 원행렬을 만들자.
np.dot(U_, np.dot(SE3, V_))

array([[ 1.00000000e+00, -5.55111512e-16],
       [ 1.00000000e+00,  2.00000000e+00],
       [ 3.00000000e+00,  3.00000000e+00]])

In [96]:
# np.allclose 함수로 동일한지 확인
np.allclose(A, np.dot(U, np.dot(SE, V)))

True