In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 12-1-2-1 QR 분해

In [3]:
import numpy.linalg as LA

In [4]:
A = np.array([[12,-51,4 ], [6, 167, -68], [-4, 24, -41]])

In [5]:
A

array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])

In [6]:
Q, R = LA.qr(A)

In [7]:
R 

array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])

###  직교행렬 알아보기

In [8]:
Q

array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])

In [9]:
i = np.dot(Q, Q.T)

In [10]:
i

array([[ 1.00000000e+00,  9.70056801e-17, -2.53402741e-17],
       [ 9.70056801e-17,  1.00000000e+00, -2.88873234e-17],
       [-2.53402741e-17, -2.88873234e-17,  1.00000000e+00]])

In [11]:
I = np.eye(A.shape[0])

In [12]:
np.allclose(i,I)

True

###  직교행렬의 행렬식은 1, 단위행렬과 동일

In [13]:
sq = np.fabs(LA.linalg.det(Q))

In [14]:
sq

0.9999999999999999

In [15]:
np.allclose(sq, 1)

True

In [16]:
qt = LA.inv(Q)

In [17]:
np.allclose(Q.T, qt)

True