In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 

https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html

## 예제 12-1-1-1 LU 분해하기

In [3]:
import scipy as sp

In [4]:
from scipy import linalg as LA

In [5]:
A = np.array( [[7,3,-1,2], [3,8,1,-4], [-1,1,4,-1], [2,-4,-1,6]])

In [6]:
A

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])

In [7]:
P, L, U = LA.lu(A)

In [8]:
P

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])

In [10]:
U

array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])

In [11]:
a = LA.det(L)

In [12]:
a

1.0

In [13]:
b = LA.det(U)

In [14]:
b

315.00000000000006

In [15]:
np.dot(a,b)

315.00000000000006

In [16]:
LA.det(A)

315.00000000000006

## 예제 10-3-1-2 LU 분해와 연립방정식 풀기 

In [17]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])

In [18]:
lu, piv = LA.lu_factor(A)

In [19]:
lu

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.28571429,  3.57142857,  6.28571429,  5.28571429],
       [ 0.71428571,  0.12      , -1.04      ,  3.08      ],
       [ 0.71428571, -0.44      , -0.46153846,  7.46153846]])

In [20]:
piv

array([2, 2, 3, 3], dtype=int32)

In [21]:
P,L,U = LA.lu(A)

In [22]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.28571429,  1.        ,  0.        ,  0.        ],
       [ 0.71428571,  0.12      ,  1.        ,  0.        ],
       [ 0.71428571, -0.44      , -0.46153846,  1.        ]])

In [23]:
U

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  6.28571429,  5.28571429],
       [ 0.        ,  0.        , -1.04      ,  3.08      ],
       [ 0.        ,  0.        ,  0.        ,  7.46153846]])

In [24]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
b = np.array([1, 1, 1, 1])


In [25]:
lu, piv = LA.lu_factor(A)

In [26]:
x =LA.lu_solve((lu, piv), b)

In [27]:
x

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [28]:
np.allclose(A @ x - b, np.zeros((4,)))

True

In [29]:
x_ = np.linalg.solve(A,b)

In [30]:
x_

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [31]:
 np.dot(np.linalg.inv(A), b) 

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [32]:
np.dot(A, x_)

array([1., 1., 1., 1.])

In [33]:
A @ x

array([1., 1., 1., 1.])