In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.2'

## 예제 2-2-2 랭크 알아보기

In [3]:
v1 =  np.array([1,2,3,4])

In [4]:
np.linalg.matrix_rank(v1)

1

In [5]:
c = np.array([[1,2,4],[2,4,8]])

In [6]:
c

array([[1, 2, 4],
       [2, 4, 8]])

In [7]:
np.linalg.matrix_rank(c)

1

In [8]:
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])

In [9]:
c1

array([[1, 2, 4],
       [2, 4, 8],
       [3, 4, 5]])

In [10]:
np.linalg.matrix_rank(c1)

2

In [11]:
np.linalg.det(c1)

0.0

In [12]:
c1[0] *2  - c1[1]

array([0, 0, 0])

In [13]:
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])

In [14]:
np.linalg.matrix_rank(c2)

3

In [15]:
np.linalg.det(c2)

-17.0

In [16]:
np.linalg.matrix_rank(c2.T)

3

In [17]:
c3 = np.array([[1,2,3],[4,5,6],[0,0,0]])

In [18]:
c3

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [20]:
np.linalg.matrix_rank(c3)

2

In [21]:
np.linalg.det(c3)

0.0