In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.0'

## 예제 1-5-1-1 파이썬 리스트와 배열 처리

In [82]:
l = [1,2,3,4]

In [83]:
l.append(5)

In [84]:
l

[1, 2, 3, 4, 5]

In [85]:
l2 = [[1,2,3,4],[4,5,6,7]]

In [86]:
l2.append([5,6,7,8])

In [87]:
l2

[[1, 2, 3, 4], [4, 5, 6, 7], [5, 6, 7, 8]]

In [88]:
a = np.array([1,2,3,4])

In [89]:
a = np.append(a,5)

In [90]:
a

array([1, 2, 3, 4, 5])

In [91]:
 b = np.append(a,[3,4,5,6],axis=0)

In [92]:
b

array([1, 2, 3, 4, 5, 3, 4, 5, 6])

In [93]:
c = a[np.newaxis, :]

In [94]:
c

array([[1, 2, 3, 4, 5]])

In [95]:
d = np.append(c, np.array([[3,4,5,6,7]]),axis=0)

In [96]:
d

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [97]:
ll = [1,2,3,4,5]

In [98]:
ll

[1, 2, 3, 4, 5]

In [99]:
ll.insert(2,99)

In [100]:
ll

[1, 2, 99, 3, 4, 5]

In [101]:
aa = np.array([1,2,3,4,5])

In [102]:
aa

array([1, 2, 3, 4, 5])

In [103]:
aa = np.insert(aa, 2, 99)

In [104]:
aa

array([ 1,  2, 99,  3,  4,  5])

In [ ]:
ll.remove(99)

In [105]:
ll

[1, 2, 99, 3, 4, 5]

In [106]:
cc = np.delete(aa,2)

In [107]:
cc

array([1, 2, 3, 4, 5])

In [108]:
dd = np.arange(6)

In [109]:
dd = dd.reshape(3,2)

In [110]:
dd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [111]:
ee = np.delete(dd,1)

In [112]:
ee

array([0, 2, 3, 4, 5])

In [113]:
ff = np.delete(dd,(0,1))

In [114]:
ff

array([2, 3, 4, 5])

In [115]:
gg = np.delete(dd,0,axis=0)

In [116]:
gg

array([[2, 3],
       [4, 5]])

In [117]:
hh = np.delete(dd,0,axis=1)

In [118]:
hh

array([[1],
       [3],
       [5]])

In [120]:
lll = [np.log(x) for x in np.arange(1,10)]

In [121]:
lll

[0.0,
 0.6931471805599453,
 1.0986122886681098,
 1.3862943611198906,
 1.6094379124341003,
 1.791759469228055,
 1.9459101490553132,
 2.0794415416798357,
 2.1972245773362196]

## 예제 1-5-2-1 파이썬 문장에  배열 사용하기

In [3]:
a = np.array([True, False])

In [4]:
if a[0] :
    print(" True")

 True


In [5]:
try :
    if a :
        print(" True")
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [6]:
if a.any() :
    print("True") 
else :
    print("False")

True


In [7]:
if a.all() :
    print("True") 
else :
    print("False")

False


In [8]:
b = np.array([1,2,3,4])

In [9]:
b > 5

array([False, False, False, False])

In [10]:
try :
    if b.any(b > 5) :
        print("True") 
    else :
        print("False")
        
except Exception as e :
    print(e)

only integer scalar arrays can be converted to a scalar index


In [11]:
if np.any(b > 5) :
    print("True") 
else :
    print("False")

False


In [12]:
b < 5

array([ True,  True,  True,  True])

In [13]:
if np.all(b > 5) :
    print("True") 
else :
    print("False")

False


In [14]:
na = np.arange(5.0)

In [15]:
na

array([0., 1., 2., 3., 4.])

In [16]:
import collections as cols

In [17]:
issubclass(type(na), cols.Iterable)

True

In [18]:
issubclass(type(na), cols.Iterator)

False

In [19]:
for i in na :
    print(i)

0.0
1.0
2.0
3.0
4.0


## 예제 1-5-3-1  자료형 변환해서 사용하기 

In [20]:
x = np.arange(4).reshape(2,2)

In [21]:
y = np.nditer(x)

In [22]:
y

In [23]:
import collections as cols

In [24]:
type(y)

numpy.nditer

In [25]:
issubclass(type(y), cols.Iterator)

True

In [26]:
next(y),next(y),next(y),next(y)

(array(0), array(1), array(2), array(3))

In [27]:
next(y)

StopIteration: 

In [28]:
a = np.arange(0,60,5)

In [29]:
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [30]:
b = a.reshape(3,4)

In [31]:
b

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [32]:
np.isfortran(b)

False

In [33]:
c = b.copy(order='F')

In [34]:
c

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [35]:
np.isfortran(c)

True

In [36]:
c.T

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [37]:
np.isfortran(c.T)

False

In [38]:
for i in np.nditer(c) :
    print(i)

0
20
40
5
25
45
10
30
50
15
35
55


In [39]:
x = np.arange(0,60,5).reshape(3,4)

In [40]:
x

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [41]:
y = np.arange(4)

In [42]:
y

array([0, 1, 2, 3])

In [43]:
for i,j in np.nditer([x,y]) :
    print(i, j)

0 0
5 1
10 2
15 3
20 0
25 1
30 2
35 3
40 0
45 1
50 2
55 3


In [44]:
x[...]

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [45]:
y =  np.nditer(x, op_flags=['readwrite']) 

In [46]:
y

In [47]:
y.itviews

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]),)

In [48]:
for k in y :
    k[...] =  k*10

In [49]:
x

array([[  0,  50, 100, 150],
       [200, 250, 300, 350],
       [400, 450, 500, 550]])

## 예제 1-5-4-1  파이썬 클래스 이용하기

In [50]:
import collections as cols

In [51]:
print(type(range(5)))

<class 'range'>


In [52]:
issubclass(range, cols.Iterable)

True

In [53]:
issubclass(range, cols.Iterator)

False

In [54]:
x = np.fromiter(range(5), dtype=np.int_)

In [55]:
x

array([0, 1, 2, 3, 4])

In [56]:
type((i for i in range(5)))

generator

In [57]:
issubclass(type((i for i in range(5))), cols.Iterator)

True

In [58]:
issubclass(type((i for i in range(5))), cols.Generator)

True

In [59]:
y = np.fromiter((i for i in range(5)), dtype=np.int_)

In [60]:
y

array([0, 1, 2, 3, 4])

In [61]:
def gen(x) :
    for i in range(x) :
        yield i

In [62]:
z = np.fromiter(gen(5), dtype=np.int_)

In [63]:
z

array([0, 1, 2, 3, 4])

In [64]:
from decimal import Decimal

In [65]:
d1 = Decimal(100.11)

In [66]:
d2 = Decimal(99.99)

In [67]:
a  = np.array([d1,d2])

In [68]:
a

array([Decimal('100.1099999999999994315658113919198513031005859375'),
       Decimal('99.9899999999999948840923025272786617279052734375')],
      dtype=object)

In [69]:
b = np.sum(a)

In [70]:
b

Decimal('200.0999999999999943156581139')

In [71]:
d3 = Decimal('88.88')

In [72]:
d3

Decimal('88.88')

In [73]:
d4 = Decimal('33.88')

In [74]:
d4

Decimal('33.88')

In [75]:
c  = np.array([d3,d4])

In [76]:
d = np.sum(c)

In [77]:
d

Decimal('122.76')

In [78]:
s = b"Hello"

In [79]:
sa = np.frombuffer(s, dtype='S1')

In [80]:
sa

array([b'H', b'e', b'l', b'l', b'o'], dtype='|S1')

In [81]:
sa.size

5