In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## 예제 1-4-1-1 숫자 자료형 변환 

In [3]:
a = np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.dtype

dtype('int64')

In [6]:
a = a + 1.5

In [7]:
a

array([[2.5, 3.5, 4.5],
       [5.5, 6.5, 7.5]])

In [8]:
a.dtype

dtype('float64')

In [10]:
b = a + 2.3

In [11]:
b

array([[4.8, 5.8, 6.8],
       [7.8, 8.8, 9.8]])

In [12]:
a

array([[2.5, 3.5, 4.5],
       [5.5, 6.5, 7.5]])

In [13]:
a is b

False

In [14]:
a = a + 1+5j

In [15]:
a

array([[3.5+5.j, 4.5+5.j, 5.5+5.j],
       [6.5+5.j, 7.5+5.j, 8.5+5.j]])

In [16]:
a.dtype

dtype('complex128')

In [18]:
b = np.array([[1,2,3],[4,5,6]])

In [19]:
c = b.astype(np.float_)

In [20]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
c.dtype

dtype('float64')

In [23]:
d = c.astype(np.int_)

In [24]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
d.dtype

dtype('int64')

In [26]:
b == d

array([[ True,  True,  True],
       [ True,  True,  True]])

## 예제 1-4-2-1 정밀도 알아보기

In [27]:
f = np.finfo(np.float64)

In [28]:
type(f)

numpy.finfo

In [29]:
count = 0 
for i in dir(f) :
    if not i.startswith("_") :
        count += 1
        print(i, end=" ") 
        if count % 5 == 0 :
            print()

bits dtype eps epsneg iexp 
machar machep max maxexp min 
minexp negep nexp nmant precision 
resolution tiny 

In [30]:
f.max

1.7976931348623157e+308

In [31]:
f.min

-1.7976931348623157e+308

In [32]:
f.precision

15

In [33]:
f.eps

2.220446049250313e-16

In [34]:
x = 1

In [35]:
y = x + (2 * f.eps)

In [36]:
y

1.0000000000000004

In [45]:
y == 1.0

False

In [44]:
np.allclose(y, 1.0)

True

In [37]:
z = (x + f.eps/2)

In [38]:
z

1.0

In [39]:
y == z

False

In [40]:
np.allclose(y,z)

True

In [33]:
z == x

True

In [34]:
np.allclose(x,z)

True

In [35]:
i = np.iinfo(np.int32)

In [36]:
type(i)

numpy.core.getlimits.iinfo

In [37]:
count = 0 
for i in dir(i) :
    if not i.startswith("_") :
        count += 1
        print(i, end=" ") 
        if count % 5 == 0 :
            print()

bits dtype key kind max 
min 

## 예제 1-4-3-1  help 와 동일한 검색하기

In [38]:
np.info(np.info)

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000002805BDA42B0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [39]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr