In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

## 예제 9-2-1-1  최소값과 최대값 확인하기 

In [3]:
a = np.array([1,3,7,9])

In [4]:
a

array([1, 3, 7, 9])

In [5]:
np.max(a)

9

In [6]:
np.min(a)

1

In [7]:
b = np.random.randn(3,4)

In [8]:
b

array([[-0.59597417,  1.54171967,  1.76554017, -1.14668407],
       [ 1.25494231, -1.37936735,  0.90410828,  0.81920124],
       [-1.09612937,  0.58750686, -1.11619244,  1.35110011]])

In [9]:
np.max(b, axis=0)

array([1.25494231, 1.54171967, 1.76554017, 1.35110011])

In [10]:
np.max(b, axis=1)

array([1.76554017, 1.25494231, 1.35110011])

In [12]:
c = np.array([[3,7,5], [8,4,3],[2,4,9]])

In [13]:
c

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [14]:
np.amin(c)

2

In [15]:
np.amin(c, 0)

array([2, 4, 3])

In [16]:
np.amin(c, 1)

array([3, 3, 2])

In [18]:
d = np.random.randn(3,4)

In [19]:
d

array([[ 0.6484186 ,  0.24095554,  1.53372549, -1.10418271],
       [-2.43381466,  1.06428704,  0.99646325, -1.62301596],
       [ 0.68911584,  1.02909299,  2.13538043,  1.203938  ]])

In [20]:
np.argmax(d)

10

In [21]:
np.argmax(d,axis=0)

array([2, 1, 2, 2], dtype=int64)

In [22]:
np.argmin(d,axis=0)

array([1, 0, 1, 1], dtype=int64)