In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

##  예제 5-1-4-1  하나의 배열을 분리하기

In [3]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.vstack([a,a])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
x,y = np.split(b,[2])

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a,b,c = np.split(b,[1,3])

In [13]:
a

array([[1, 2, 3]])

In [14]:
b

array([[4, 5, 6],
       [1, 2, 3]])

In [15]:
c

array([[4, 5, 6]])

In [19]:
bb = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)

In [23]:
bb

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
h1,h2 = np.split(bb,[2], axis=1)

In [21]:
h1

array([[1, 2],
       [4, 5]])

In [22]:
h2

array([[3],
       [6]])

## 예제 5-1-4-2  배열을 분리하기

In [25]:
v1 = np.array([[1,2,3],[4,5,6]])

In [24]:
v2 = np.array([[11,12,13],[14,15,16]])

In [26]:
v = np.vstack([v1,v2])

In [27]:
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [29]:
x,y = np.vsplit(v,[2])

In [30]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
y

array([[11, 12, 13],
       [14, 15, 16]])

In [33]:
x1,y1,z1 = np.vsplit(v,[1,3])

In [34]:
x1

array([[1, 2, 3]])

In [35]:
y1

array([[ 4,  5,  6],
       [11, 12, 13]])

In [36]:
z1

array([[14, 15, 16]])

In [37]:
h = np.hstack([v1,v2])

In [38]:
h

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [43]:
x2,y2,z2 = np.hsplit(h,[1,3])

In [44]:
x2

array([[1],
       [4]])

In [45]:
y2

array([[2, 3],
       [5, 6]])

In [46]:
z2

array([[11, 12, 13],
       [14, 15, 16]])

## 예제 5-1-4-3  배열에 축과 모양을 주고 분리하기

In [3]:
a = np.arange(16).reshape(4,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
 c = np.array_split(a,(2,), axis=0)

In [14]:
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [15]:
 c_ = np.array_split(a,(3,), axis=0)

In [16]:
c_

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [17]:
d = np.array_split(a,(2,), axis=1)

In [20]:
d[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
d[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])