In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

##  예제 5-2-3-1  숫자값 체크

In [3]:
m = np.random.randn(3,5) 

In [4]:
m

array([[-1.33538049,  1.35364126, -1.51628494,  0.96066108, -0.48526836],
       [-0.01390562, -1.16356996, -0.17705748, -1.70110368,  0.22327142],
       [ 0.9295063 , -0.96870455,  0.41981469, -0.14013011, -0.52879405]])

In [5]:
np.isreal(m)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
np.isinf(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
np.isnan(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [35]:
x = np.array([1,2+3j,3,4],dtype=np.complex64)

In [36]:
np.iscomplex(x)

array([False,  True, False, False])

In [37]:
x.real

array([1., 2., 3., 4.], dtype=float32)

In [38]:
x.imag

array([0., 3., 0., 0.], dtype=float32)

##  예제 5-2-3-2  제로 값 체크

In [24]:
a = np.zeros((3,5))

In [25]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.nonzero(a)

(array([], dtype=int64), array([], dtype=int64))

In [27]:
a[2,2] = 100

In [28]:
a[2,3] = 99

In [29]:
a

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100.,  99.,   0.]])

In [30]:
np.nonzero(a)

(array([2, 2], dtype=int64), array([2, 3], dtype=int64))