In [1]:
import numpy as np

In [2]:
np.__version__

'1.17.3'

## 예제 5-3-4-1  미러링, 대칭, 래핑 처리하기

In [3]:
x = np.arange(1,5).reshape(2,2)

In [4]:
x

array([[1, 2],
       [3, 4]])

In [5]:
np.pad(x,(0,1),"reflect")

array([[1, 2, 1],
       [3, 4, 3],
       [1, 2, 1]])

In [6]:
np.pad(x,(1,0),"reflect")

array([[4, 3, 4],
       [2, 1, 2],
       [4, 3, 4]])

In [4]:
np.pad(x,(1,1),"reflect")

array([[4, 3, 4, 3],
       [2, 1, 2, 1],
       [4, 3, 4, 3],
       [2, 1, 2, 1]])

In [5]:
np.pad(x,(3,3),"reflect")

array([[4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1]])

In [9]:
np.pad(x,(1,1),"symmetric")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [10]:
np.pad(x,(2,2),"symmetric")

array([[4, 3, 3, 4, 4, 3],
       [2, 1, 1, 2, 2, 1],
       [2, 1, 1, 2, 2, 1],
       [4, 3, 3, 4, 4, 3],
       [4, 3, 3, 4, 4, 3],
       [2, 1, 1, 2, 2, 1]])

In [11]:
np.pad(x,(3,3),"symmetric")

array([[4, 4, 3, 3, 4, 4, 3, 3],
       [4, 4, 3, 3, 4, 4, 3, 3],
       [2, 2, 1, 1, 2, 2, 1, 1],
       [2, 2, 1, 1, 2, 2, 1, 1],
       [4, 4, 3, 3, 4, 4, 3, 3],
       [4, 4, 3, 3, 4, 4, 3, 3],
       [2, 2, 1, 1, 2, 2, 1, 1],
       [2, 2, 1, 1, 2, 2, 1, 1]])

In [12]:
np.pad(x,(1,1),"wrap")

array([[4, 3, 4, 3],
       [2, 1, 2, 1],
       [4, 3, 4, 3],
       [2, 1, 2, 1]])

In [13]:
np.pad(x,(2,2),"wrap")

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [14]:
np.pad(x,(3,3),"wrap")

array([[4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1, 2, 1]])