In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
np.ufunc

numpy.ufunc

### 예제 1. 유니버설 함수 클래스 알아보기

In [3]:
type(np.add)

numpy.ufunc

In [4]:
for i in dir(np.ufunc) :
    if not i.startswith("_") :
        print(i)

accumulate
at
identity
nargs
nin
nout
ntypes
outer
reduce
reduceat
signature
types


In [5]:
dir(np.ufunc)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

### 예제 2. add 함수를 사용해서 메소드 처리하기

In [8]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import functools as ft

# reduce(집계함수, 순회 가능한 데이터, [초기값-생략가능])
# 특정함수와 반복형 객체를 받아 연산을 처리하고 결과를 반환해 줌

ft.reduce(np.add, a) 

45

In [10]:
np.add.reduce(a)

45

In [11]:
a.sum()

45

In [21]:
# reduceat 메소드로 배열의 특정 위치를 지정해서 합산
np.add.reduceat(a, [0, 4])

array([ 6, 39])

In [22]:
np.add.reduce(a[:4])

6

In [23]:
np.add.reduce(a[4:])

39

In [24]:
np.add.reduceat(a, [0, 4, 1, 5])

array([ 6,  4, 10, 35])

In [30]:
print(np.add.reduce(a[:4]))
print(np.add.reduce(a[4:5])) # 인덱스 주의!
print(np.add.reduce(a[1:5]))
print(np.add.reduce(a[5:]))

6
4
10
35


## Quiz 1
>>> np.add.reduceat(np.arange(8), [0, 4, 1, 5, 2, 6, 3, 7])[::2]
>>> array([6, 10, 14, 18])
위 결과값을 나온 이유를 설명해 주세요.

In [44]:
print(np.add.reduceat([0,1,2,3,4,5,6,7], [0, 4]))
print(np.add.reduceat([0,1,2,3,4,5,6,7], [4, 1]))
print(np.add.reduceat([0,1,2,3,4,5,6,7], [1, 5]))
print(np.add.reduceat([0,1,2,3,4,5,6,7], [5, 2]))
print(np.add.reduceat([0,1,2,3,4,5,6,7], [2, 6]))
print(np.add.reduceat([0,1,2,3,4,5,6,7], [6, 3]))
print(np.add.reduceat([0,1,2,3,4,5,6,7], [3, 7]))

x = np.add.reduceat([0,1,2,3,4,5,6,7], [0, 4, 1, 5, 2, 6, 3, 7])
print(x)

x[::2]

[ 6 22]
[ 4 28]
[10 18]
[ 5 27]
[14 13]
[ 6 25]
[18  7]
[ 6  4 10  5 14  6 18  7]


array([ 6, 10, 14, 18])

### 예제3. logical_and 함수로 알아보기

In [45]:
type(np.logical_and)

numpy.ufunc

In [49]:
y = np.array([[2, 5], [7, 8]])
z = np.array([[2, 3], [2, 8]])
a = y > z
a

array([[False,  True],
       [ True, False]])

In [47]:
b = np.logical_and.reduce(y>z) # 행에 있는 논리값들을 다시 비교해서 결과 출력
b

array([False, False])

In [51]:
# 논리값의 결과를 더 줄이는 .any와 .all
(y>z).all()

False

In [52]:
(y>z).any()

True