In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 11-3-1-1  필드 생성하기 

In [3]:
fd = np.dtype([('F4', np.int64)])

In [4]:
fd

dtype([('F4', '<i8')])

In [5]:
data = np.zeros((3,3), dtype=fd)

In [6]:
data

array([[(0,), (0,), (0,)],
       [(0,), (0,), (0,)],
       [(0,), (0,), (0,)]], dtype=[('F4', '<i8')])

In [7]:
data[0]

array([(0,), (0,), (0,)], dtype=[('F4', '<i8')])

In [8]:
data[0,1]

(0,)

In [9]:
data['F4']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [10]:
data[0]['F4']

array([0, 0, 0], dtype=int64)

In [11]:
data[0,1]['F4']

0

In [12]:
df2 = [('X', np.int64), ('Y',np.float64)]

In [13]:
data2 = np.array([(10,100.3), (20,200.6)], dtype=df2)

In [14]:
data2

array([(10, 100.3), (20, 200.6)], dtype=[('X', '<i8'), ('Y', '<f8')])

In [15]:
data2[0]

(10, 100.3)

In [16]:
data2[0]['X']

10

In [17]:
data2[0]['Y']

100.3

In [18]:
data2[1]

(20, 200.6)

In [19]:
data2[1]['X']

20

In [20]:
data2[1]['Y']

200.6

In [21]:
data2['X']

array([10, 20], dtype=int64)

In [22]:
data2['Y']

array([100.3, 200.6])

In [23]:
df3 = [('X','f4'), ('Y', np.float32), ('Z',np.int32)]

In [24]:
x = np.zeros(3, dtype=df3)

In [25]:
x

array([(0., 0., 0), (0., 0., 0), (0., 0., 0)],
      dtype=[('X', '<f4'), ('Y', '<f4'), ('Z', '<i4')])

In [26]:
x['X']

array([0., 0., 0.], dtype=float32)

In [27]:
x['Y']

array([0., 0., 0.], dtype=float32)

In [28]:
x['Z']

array([0, 0, 0])