In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 11-1-1-1  유니버셜 함수 클래스 알아보기

In [3]:
np.ufunc

numpy.ufunc

In [4]:
type(np.add)

numpy.ufunc

In [5]:
for i in dir(np.ufunc) :
    if not i.startswith("_") :
        print(i)

accumulate
at
identity
nargs
nin
nout
ntypes
outer
reduce
reduceat
signature
types


## 예제 11-1-1-2  add 함수을 이용해서 메소드 처리하기

In [6]:
a = np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
import functools as ft

In [9]:
ft.reduce(np.add,a)

45

In [10]:
np.add.reduce(a)

45

In [11]:
a.sum()

45

In [12]:
np.add.reduceat(a,[0,4])

array([ 6, 39], dtype=int32)

In [13]:
np.add.reduce(a[:4])

6

In [14]:
np.add.reduce(a[4:])

39

In [15]:
np.add.reduceat(a,[0,4,1,5])

array([ 6,  4, 10, 35], dtype=int32)

In [16]:
np.add.reduce(a[:4])

6

In [17]:
np.add.reduce(a[4:5])

4

In [18]:
np.add.reduceat(a[:5],[0,4]).sum()

10

In [19]:
np.add.reduce(a[5:])

35

## 예제 11-1-1-3  logical_and 함수로 알아보기

In [20]:
type(np.logical_and)

numpy.ufunc

In [21]:
y = np.array([[2,5],[7,8]])

In [22]:
z = np.array([[2,3],[2,8]])

In [23]:
a = y > z

In [24]:
a

array([[False,  True],
       [ True, False]])

In [25]:
b = np.logical_and.reduce(y>z)

In [26]:
b

array([False, False])

In [27]:
(y>z).all()

False

In [28]:
(y>z).any()

True