## 예제 1-1-1-1 리스트 구조

In [1]:
l = [[1,2,3],[4,5,6]]

In [2]:
type(l)

list

In [3]:
l[0]

[1, 2, 3]

In [4]:
l[1]

[4, 5, 6]

In [5]:
for i,a in enumerate(l) :
    for j,b in enumerate(a) :
        print(l[i][j])

1
2
3
4
5
6


## 예제 1-1-2-1 넘파이 배열  구조

In [6]:
import numpy as np

In [7]:
np.__version__

'1.18.2'

In [8]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [9]:
np.ndarray.__name__

'ndarray'

In [10]:
type(np.ndarray.var)

method_descriptor

In [11]:
for i in dir(np.ndarray) :
    if not i.startswith("_") :
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var)  :
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


## 예제 1-1-2-2 넘파이 배열  생성해보기

In [12]:
l = [1,2,3,4]

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
type(a)

numpy.ndarray

In [16]:
t = (1,2,3,4)

In [17]:
b = np.array(t)

In [18]:
type(b)

numpy.ndarray

In [19]:
a.data

In [20]:
a.data.obj

array([1, 2, 3, 4])

In [21]:
type(a.data.obj)

numpy.ndarray

In [22]:
c = b

In [23]:
c.base is None

True

In [24]:
c[0] = 100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
b

array([100,   2,   3,   4])

In [27]:
d = np.array(b)

In [28]:
d[0] = 99

In [29]:
d

array([99,  2,  3,  4])

In [30]:
b

array([100,   2,   3,   4])

In [31]:
e = np.array(l,dtype=np.float)

In [32]:
e

array([1., 2., 3., 4.])

In [33]:
e.dtype

dtype('float64')

In [34]:
a2 = np.array([[1,2,3],[4,5,6]])

In [35]:
a2.shape

(2, 3)

In [36]:
a2.ndim

2

In [37]:
a2.dtype

dtype('int32')

In [38]:
a2.itemsize

4

In [39]:
a2.size

6

In [40]:
a2.strides

(12, 4)

In [41]:
a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [42]:
a2.ravel()

array([1, 2, 3, 4, 5, 6])

## 예제 1-1-2-3 넘파이 배열  원소 조회하기

In [43]:
a

array([1, 2, 3, 4])

In [44]:
l

[1, 2, 3, 4]

In [45]:
a[0]

1

In [46]:
l[0]

1

In [47]:
l2 = [[1,2,3],[4,5,6]]

In [48]:
l2

[[1, 2, 3], [4, 5, 6]]

In [49]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
try :
    l2[0,1]
except Exception as e :
    print(e)

list indices must be integers or slices, not tuple


In [51]:
l2[0][1]

2

In [52]:
a2[0,1]

2

In [53]:
a2[(0,1)]

2

In [54]:
type(a2[0,1])

numpy.int32

In [55]:
a2[0,1].item()

2

In [56]:
type(a2[0,1].item())

int

In [57]:
a2[0,1].real

2

In [58]:
a2[0,1].imag

0

## 예제 1-1-3-1 넘파이 배열 내부구조 확인

In [59]:
na = np.array([[[1,2,3,],[4,5,6]],[[1,2,3,],[4,5,6]]])

In [60]:
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [61]:
na.ndim

3

In [62]:
na.shape

(2, 2, 3)

In [63]:
na[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
na[0].shape

(2, 3)

In [65]:
na.__array_interface__

{'data': (1480277827120, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (2, 2, 3),
 'version': 3}

In [66]:
na.strides

(24, 12, 4)

In [67]:
na.__array_interface__['data'][0]

1480277827120

In [68]:
len(na.data.tobytes())

48

In [69]:
na.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

## 예제 1-1-3-2 data 속성 관리 기준

In [70]:
a = np.array([1,2,3,4])

In [71]:
a

array([1, 2, 3, 4])

In [72]:
a.data

In [73]:
mem = memoryview(a)

In [74]:
mem

In [75]:
a.data[0]

1

In [76]:
a.data.obj

array([1, 2, 3, 4])

In [77]:
a.data.obj[0]

1

In [78]:
a.dtype

dtype('int32')

In [79]:
a.itemsize

4

In [80]:
a.data.hex()

'01000000020000000300000004000000'

In [81]:
b = np.array([999,9999,99999,999999])

In [82]:
b.data.hex()[:8]

'e7030000'

In [83]:
hex(999)

'0x3e7'

In [84]:
int('0x3e7', 16)

999

In [85]:
divmod(999,16)

(62, 7)

In [86]:
divmod(62,16)

(3, 14)

In [87]:
divmod(3,16)

(0, 3)

In [88]:
a.size

4

In [89]:
for i in range(a.size) :
    print(a[i])

1
2
3
4


In [90]:
a.flat

In [91]:
for i in a.flat :
    print(i)

1
2
3
4


In [92]:
c = np.array([1,2,3,4],dtype=np.float_)

In [93]:
c

array([1., 2., 3., 4.])

In [94]:
x = np.frombuffer(c)

In [95]:
x

array([1., 2., 3., 4.])

In [96]:
x.dtype

dtype('float64')

In [97]:
x[0]

1.0

In [98]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [99]:
x.base is c 

True

In [100]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## 예제 1-1-4-1 두 클래스 비교

In [101]:
np.ndarray.__bases__

(object,)

In [102]:
np.matrix.__bases__

(numpy.ndarray,)

In [103]:
l1 = np.array([1,2,3,4,5,6,7,8])

In [104]:
l1.shape

(8,)

In [105]:
m1 = np.matrix([1,2,3,4,5,6,7,8])

In [106]:
m1.shape

(1, 8)

In [107]:
l2 = l1.reshape(2,4)

In [108]:
l2.shape

(2, 4)

In [109]:
m2 = m1.reshape(2,4)

In [110]:
m2.shape

(2, 4)

In [111]:
l3 = l2.reshape(2,2,2)

In [112]:
try :
    m3 = m2.reshape(2,2,2) 
except Exception as e :
    print(" 예외 ",e)

 예외  shape too large to be a matrix.


In [113]:
m2_1 = np.asmatrix(l1).reshape(2,4)

In [114]:
m2_1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [115]:
l2 * l2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [116]:
try :
    m2 * m2
except Exception as e :
    print(e)

shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)


In [117]:
np.multiply(m2,m2)

matrix([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

## 예제 1-1-4-2 두 클래스 차이점 확인

In [118]:
nd_ = set(dir(np.ndarray))

In [119]:
md_ = set(dir(np.matrix))

In [120]:
md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [121]:
m4 = np.mat('1 2; 3 4')

In [122]:
m4

matrix([[1, 2],
        [3, 4]])

In [123]:
m4.A

array([[1, 2],
       [3, 4]])

In [124]:
m4.getA()

array([[1, 2],
       [3, 4]])

In [125]:
m4.H

matrix([[1, 3],
        [2, 4]])

In [126]:
m4.T

matrix([[1, 3],
        [2, 4]])

In [127]:
from numpy import linalg

In [128]:
linalg.inv(m4)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [129]:
m4.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [130]:
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [131]:
try :
    linalg.inv(m2)
except Exception as e :
    print(e)

Last 2 dimensions of the array must be square


In [132]:
m2.I

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -2.10437669e-17],
        [ 4.25000000e-01, -1.25000000e-01]])