In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-2-1 논리식으로 검색하기 

In [3]:
L = np.random.randn(7,4)

In [4]:
L

array([[ 0.52875664,  0.60780693, -0.16296562, -0.88084688],
       [ 1.48912701, -0.13582955, -0.59338754,  0.19616622],
       [-0.70345747,  0.00452618, -2.43213636,  1.27205903],
       [ 0.0801979 ,  0.79916224, -0.41069601, -0.08494175],
       [-0.14080396, -0.25054823,  1.4296857 ,  0.34680384],
       [ 0.94921755, -1.02812083, -0.97749395,  1.65779443],
       [ 0.20343849, -0.12627667, -0.24716326,  0.18280498]])

In [5]:
L < 0

array([[False, False,  True,  True],
       [False,  True,  True, False],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [False,  True,  True, False]])

In [6]:
L[ L < 0 ]

array([-0.16296562, -0.88084688, -0.13582955, -0.59338754, -0.70345747,
       -2.43213636, -0.41069601, -0.08494175, -0.14080396, -0.25054823,
       -1.02812083, -0.97749395, -0.12627667, -0.24716326])

In [7]:
L[ L < 0 ] = 999

In [8]:
L

array([[5.28756640e-01, 6.07806927e-01, 9.99000000e+02, 9.99000000e+02],
       [1.48912701e+00, 9.99000000e+02, 9.99000000e+02, 1.96166218e-01],
       [9.99000000e+02, 4.52617783e-03, 9.99000000e+02, 1.27205903e+00],
       [8.01978978e-02, 7.99162238e-01, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 1.42968570e+00, 3.46803835e-01],
       [9.49217545e-01, 9.99000000e+02, 9.99000000e+02, 1.65779443e+00],
       [2.03438486e-01, 9.99000000e+02, 9.99000000e+02, 1.82804975e-01]])

In [9]:
LC = L[ L == 999 ] 

In [10]:
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999.])

In [11]:
LC[0] = 1000

In [12]:
LC

array([1000.,  999.,  999.,  999.,  999.,  999.,  999.,  999.,  999.,
        999.,  999.,  999.,  999.,  999.])

In [13]:
L == 1000

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [14]:
LL = L

In [15]:
np.may_share_memory(LC, L)

False

In [16]:
np.may_share_memory(LL, L)

True