In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-2-2  다양한 논리식 적용하기

In [3]:
L = np.arange(0,12).reshape(3,4)

In [4]:
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
L[ L < 5 ]

array([0, 1, 2, 3, 4])

In [6]:
L% 3

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]], dtype=int32)

In [7]:
L[ L% 3  > 0 ]

array([ 1,  2,  4,  5,  7,  8, 10, 11])

In [8]:
L.nonzero()

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [9]:
 L[ L.nonzero()] 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])