In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-3-2-1 다차원 배열로 조회하기

In [3]:
x = np.arange(10).reshape(2,5)

In [4]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
x[tuple([[0,1],[0,1]])]

array([0, 6])

In [6]:
x[[[0,1],[0,1]],[0,1]]

array([[0, 6],
       [0, 6]])

In [7]:
y = np.reshape(np.arange(10),(2,5))

In [8]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
y[([1,1])]

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [10]:
y[[1,1]]

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [11]:
y[tuple([[1,1],[0,0]])]

array([5, 5])