In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-1-2 슬라이스 검색

In [3]:
B = np.arange(9).reshape(3,3)

In [4]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
B.shape

(3, 3)

In [6]:
B[0,:]

array([0, 1, 2])

In [7]:
B[0]

array([0, 1, 2])

In [8]:
B[:,0]

array([0, 3, 6])

In [9]:
B[:2, 1:]

array([[1, 2],
       [4, 5]])

In [10]:
B[::2, ::2]

array([[0, 2],
       [6, 8]])

In [11]:
B.flat

In [12]:
B.flat[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
B.flat[::2]

array([0, 2, 4, 6, 8])