In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-4-2-1 질의 함수 이용하기 

In [3]:
x = np.arange(9).reshape(3,3)

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.choose(0,x)

array([0, 1, 2])

In [6]:
np.choose([0],x)

array([0, 1, 2])

In [7]:
np.choose(1,x)

array([3, 4, 5])

In [8]:
np.choose(2,x)

array([6, 7, 8])

In [9]:
try :
    np.choose(3,x)
except Exception as e :
    print(e)

invalid entry in choice array


In [10]:
tuple([0,1,2])

(0, 1, 2)

In [11]:
np.choose(tuple([0,1,2]),x)

array([0, 4, 8])

In [12]:
np.choose(tuple([2,1,0]),x)

array([6, 4, 2])

In [13]:
tuple([[0],[1],[2]])

([0], [1], [2])

In [14]:
np.choose(tuple([[0],[1],[2]]),x)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.choose(tuple([[0],[1],[2],[2]]),x)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [6, 7, 8]])

In [16]:
np.where(x> 4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [17]:
x[np.where(x> 4)]

array([5, 6, 7, 8])

In [18]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
x> 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [20]:
np.select(x > 5, x)

array([6, 7, 8])

In [21]:
a = np.select(x > 5, x*2)

In [22]:
a

array([12, 14, 16])

In [23]:
np.extract(x>4, x)

array([5, 6, 7, 8])