In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 3-3-3-1 인덱스 검색과 혼용하기 

In [3]:
x = np.arange(10).reshape(2,5)

In [4]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
x[0, [0,1]]

array([0, 1])

In [6]:
x[1, [0,1]]

array([5, 6])

In [7]:
x[1, tuple([0,1])]

array([5, 6])

In [8]:
x[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
x[[0,1],0]

array([0, 5])

In [10]:
a = x[[0,1],0]

In [11]:
np.may_share_memory(x,a)

False

## 예제 3-3-3-2 슬라이스 검색과 혼용하기 

In [12]:
y = np.arange(10).reshape(2,5)

In [13]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
y[[0,1], :2]

array([[0, 1],
       [5, 6]])

In [15]:
y[:2, [0,1]]

array([[0, 1],
       [5, 6]])

In [16]:
y[[0,1], -2:]

array([[3, 4],
       [8, 9]])

In [17]:
y[-2:, [0,1]]

array([[0, 1],
       [5, 6]])

## 예제 3-3-3-3  다양한 검색 조건을 확인하기 

In [18]:
a = np.arange(6)

In [19]:
a

array([0, 1, 2, 3, 4, 5])

In [20]:
b = np.arange(0,51,10)[:,np.newaxis]

In [21]:
b

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [22]:
c = a+b

In [23]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [24]:
c[tuple([[1,3,4],[3,4,5]])]

array([13, 34, 45])

In [25]:
c[:,[0,2,5]]

array([[ 0,  2,  5],
       [10, 12, 15],
       [20, 22, 25],
       [30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [26]:
mask = np.array([1,0,1,0,0,1],dtype=bool)

In [27]:
mask

array([ True, False,  True, False, False,  True])

In [28]:
d = c[mask]

In [29]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [20, 21, 22, 23, 24, 25],
       [50, 51, 52, 53, 54, 55]])

In [30]:
np.may_share_memory(c,d)

False

In [31]:
c[mask,2]

array([ 2, 22, 52])

In [32]:
try :
    c[mask, tuple([0,1])]
except Exception as e :
    print(e)

shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 


In [33]:
c[mask][[0,1]]

array([[ 0,  1,  2,  3,  4,  5],
       [20, 21, 22, 23, 24, 25]])