In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.2'

## 예제 2-2-3-1  배열 축 알아보기

In [3]:
a = np.arange(1,10)

In [4]:
a.sum()

45

In [5]:
np.sum(a)

45

In [6]:
a.sum(axis=0)

45

In [7]:
np.sum(a,axis=0)

45

In [8]:
A = np.array([[2,3],[4,5]])

In [9]:
A.sum()

14

In [10]:
A.sum(axis=0)

array([6, 8])

In [11]:
A.sum(axis=1)

array([5, 9])

In [12]:
C = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])

In [13]:
C.ndim

3

In [14]:
C.shape

(2, 2, 2)

In [15]:
C[0]

array([[1, 2],
       [3, 4]])

In [16]:
C[1]

array([[5, 6],
       [7, 8]])

In [17]:
C.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [18]:
C.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [19]:
C.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

## 예제 2-2-3-2 배열 축 변환 알아보기

In [20]:
t = np.arange(3*4*2)

In [21]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
t1 = np.reshape(t,(3,4,2))

In [23]:
t1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [24]:
t1.shape

(3, 4, 2)

In [25]:
t2 = t1.transpose(0,2,1)

In [26]:
t2.shape

(3, 2, 4)

In [27]:
t2

array([[[ 0,  2,  4,  6],
        [ 1,  3,  5,  7]],

       [[ 8, 10, 12, 14],
        [ 9, 11, 13, 15]],

       [[16, 18, 20, 22],
        [17, 19, 21, 23]]])

In [28]:
ra = np.ones((3,4,5,3))

In [29]:
ra.shape

(3, 4, 5, 3)

In [30]:
ra.shape[3]

3

In [31]:
np.rollaxis(ra, 3, 1).shape

(3, 3, 4, 5)

In [32]:
x = np.array([[1,2,3]])

In [33]:
x.T

array([[1],
       [2],
       [3]])

In [34]:
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [35]:
ra.shape

(3, 4, 5, 3)

In [36]:
ra21 = np.swapaxes(ra, 2,1)

In [37]:
ra21.shape

(3, 5, 4, 3)