In [48]:
import numpy as np

In [49]:
np.__version__

'1.17.2'

In [50]:
import scipy.sparse as sp

##  희소행렬 
bsr_matrix(arg1[, shape, dtype, copy, blocksize])   Block Sparse Row matrix

coo_matrix(arg1[, shape, dtype, copy]) A sparse matrix in COOrdinate format.

csc_matrix(arg1[, shape, dtype, copy]) Compressed Sparse Column matrix

csr_matrix(arg1[, shape, dtype, copy]) Compressed Sparse Row matrix

dia_matrix(arg1[, shape, dtype, copy]) Sparse matrix with DIAgonal storage

dok_matrix(arg1[, shape, dtype, copy]) Dictionary Of Keys based sparse matrix.

lil_matrix(arg1[, shape, dtype, copy])Row-based linked list sparse matrix

spmatrix([maxprint])


##  Block Compressed Row : Block Sparse Row matrix


Summary of BSR format

The Block Compressed Row (BSR) format is very similar to the Compressed Sparse Row (CSR) format. BSR is appropriate for sparse matrices with dense sub matrices like the last example below. Block matrices often arise in vector-valued finite element discretizations. In such cases, BSR is considerably more efficient than CSR and CSC for many sparse arithmetic operations.

Blocksize

The blocksize (R,C) must evenly divide the shape of the matrix (M,N). That is, R and C must satisfy the relationship M % R = 0 and N % C = 0.

In [51]:
sp.bsr_matrix((3, 4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [52]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3 ,4, 5, 6])

In [57]:
BSR = sp.bsr_matrix((data, (row, col)), shape=(3, 3))

In [71]:
BSR.ndim, BSR.shape, BSR.size, BSR.dtype

(2, (3, 3), 6, dtype('int64'))

In [60]:
BSR.nnz

6

In [68]:
BSR.blocksize

(1, 1)

In [66]:
BSR.indices

array([0, 2, 2, 0, 1, 2], dtype=int32)

In [67]:
BSR.indptr

array([0, 2, 3, 6], dtype=int32)

In [59]:
BSR.toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int64)

In [63]:
BSR.data

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]], dtype=int64)

## scipy.sparse.coo_matrix : 좌표 리스트 희소 행렬 : 데이터 없이 생성하기

In [13]:
sp.coo_matrix((3, 4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

### 좌표 리스트 희소행렬 : 데이터 넣고 생성하기

In [6]:
values = [3,4,5,6]

In [17]:
rows = [0,1,2,3]
cols = [1,0,2,3]

In [18]:
A = sp.coo_matrix((values, (rows, cols)), shape=(4,4))

In [19]:
A

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>

In [25]:
A.toarray()

array([[0, 3, 0, 0],
       [4, 0, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [20]:
A.nnz, A.data

(4, array([3, 4, 5, 6]))

In [21]:
A.ndim, A.size, A.shape, A.dtype

(2, 4, (4, 4), dtype('int64'))

### 동일한 인덱스에 값이 들어가면 덧셈 처리가 됨 

In [36]:
row  = np.array([0, 0, 1, 3, 1, 0, 0])
col  = np.array([0, 2, 1, 3, 1, 0, 0])
data = np.array([1, 1, 1, 1, 1, 1, 1])
coo = sp.coo_matrix((data, (row, col)), shape=(4, 4))

In [37]:
np.max(coo.data)

1

In [38]:
coo.toarray()

array([[3, 0, 1, 0],
       [0, 2, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

## CSR 로 희소행렬 만들기

In [40]:
C = sp.csr_matrix((3, 4), dtype=np.int8)

In [41]:
C.toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [42]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
C1 = sp.csr_matrix((data, (row, col)), shape=(3, 3))

In [43]:
C1.toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int64)

In [46]:
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
C2 = sp.csr_matrix((data, indices, indptr), shape=(3, 3))

In [47]:
C2.toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

### 다른 유형으로 변경하기 

In [27]:
csr = A.tocsr()

In [28]:
csr

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [29]:
csr.toarray()

array([[0, 3, 0, 0],
       [4, 0, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]], dtype=int64)

In [26]:
lil = A.tolil()

In [31]:
lil

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in LInked List format>

In [30]:
lil.toarray()

array([[0, 3, 0, 0],
       [4, 0, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]], dtype=int64)